<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/Trainers_notes/Modules/Handson/PandasHandsOn_by_Trainer_(12th_June).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tasks to be performed:

1. Given a sample list, tuple and a set with elements as numbers from 1-10. Convert each of the data types into a pandas series. Create a separate list of index values for the series.

In [ ]:
import pandas as pd

L1=[1,2,3,4,5,6,7,8,9,10]
T1=(1,2,3,4,5,6,7,8,9,10)
S1={1,2,3,4,5,6,7,8,9,10}

i=["a","b","c","d","e","f","g","h","i","j"]

In [ ]:
Ls=pd.Series(L1, index=i)
Ts=pd.Series(T1, index=i)

In [ ]:
print(Ls,"\n",Ts)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64
 a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
Ss=pd.Series(list(S1), index=i)
print(Ss)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

2. Create a python dictionary with three key value pairs. Keep the keys as the first names, and the respective last names as values in the dictionary. Use the dictionary to create a pandas series.

In [ ]:
dict1={
    "Aisha":"Sinha",
    "Kavia":"Mariappan",
    "Amit":"Panwar"
    }

print(dict1)

s4=pd.Series(dict1)
print(s4)

{'Aisha': 'Sinha', 'Kavia': 'Mariappan', 'Amit': 'Panwar'}
Aisha        Sinha
Kavia    Mariappan
Amit        Panwar
dtype: object

3. Create a pandas series to give the values of the dictionary above index values as 0,1 and 2.

In [ ]:
dict1

{'Aisha': 'Sinha', 'Kavia': 'Mariappan', 'Amit': 'Panwar'}

In [ ]:
dict1=pd.Series(list(dict1.values()), index=[0,1,2])
print(dict1)

0        Sinha
1    Mariappan
2       Panwar
dtype: object

4. Create a sample pandas series with x integer elements.
Perform the following operations on the same:
- Print the first 5 elements of the series
- Print the last 5 elements of the series
- Insert an integer value '50' at the index 5
- Update the last element in the series with the value 100
- Delete the first element from the series

In [ ]:
s=pd.Series([1,2,3,4,5,6,7,8,9,10])
#            0 1 2 3 4 5 6 7 8 9
#First 5 elements:
s.head(5)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#Last 5 elements:
s.tail(5)

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
print(s)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
#insert at index 5 the 50 value:
s=pd.concat([s.iloc[:5],pd.Series([50]),s.iloc[5:]]).reset_index(drop=True)
print(s)

0      1
1      2
2      3
3      4
4      5
5     50
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [ ]:
#Update last value to 100:
s.iloc[-1]=100 #index 9
print(s)

0       1
1       2
2       3
3       4
4       5
5      50
6       6
7       7
8       8
9       9
10    100
dtype: int64

In [ ]:
s=s.drop(index=0).reset_index(drop=True)
print(s)

0      2
1      3
2      4
3      5
4     50
5      6
6      7
7      8
8      9
9    100
dtype: int64

5.  For a given nested list and a sample dictionary, create two data frames using pandas.
- List = [['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
- Dictionary = { 'Kris': ['Jordan',12,22],'Memphis': ['Depay', 23, 24]}

In [ ]:
L1=[['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
df_list=pd.DataFrame(L1, columns=['Col1','Col2','Col3'])
print(df_list)

  Col1 Col2 Col3
0   AA   BB   CC
1   DD   EE   FF
2   GG   HH   II

In [ ]:
D1={ 'Kris': ['Jordan',12,22],'Memphis': ['Depay', 23, 24]}
df_dict=pd.DataFrame(D1)
print(df_dict)

     Kris Memphis
0  Jordan   Depay
1      12      23
2      22      24

5. Create a pandas Dataframe with two columns = [‘Name’,‘Age’].

 Perform the following operations on the same:
- Print the first 3 rows
- Print the rows that have age greater than 15
- Insert 5 imaginary names and ages as values to this dataframe
- Update the 5th row so that the name=John and age=56
- Delete the first row from the dataframe

In [ ]:
import pandas as pd

df=pd.DataFrame({
    'Name': ['Siva','Kamal','Akshat','Gunjan','Rahul'],
    'Age':[10,13,21,31,45]
})
print(df)

     Name  Age
0    Siva   10
1   Kamal   13
2  Akshat   21
3  Gunjan   31
4   Rahul   45

In [ ]:
df.head(3)

     Name  Age
0    Siva   10
1   Kamal   13
2  Akshat   21

In [ ]:
print(df[df['Age']>15])

     Name  Age
2  Akshat   21
3  Gunjan   31
4   Rahul   45

In [ ]:
new_data=pd.DataFrame({
    'Name':['Maniram','Narendra','Lokesh','Shiva','Saurabh'],
    'Age':[22,25,12,13,20]
})
print(new_data)

df=pd.concat([df,new_data]).reset_index(drop=True)
print(df)

       Name  Age
0   Maniram   22
1  Narendra   25
2    Lokesh   12
3     Shiva   13
4   Saurabh   20
       Name  Age
0      Siva   10
1     Kamal   13
2    Akshat   21
3    Gunjan   31
4     Rahul   45
5   Maniram   22
6  Narendra   25
7    Lokesh   12
8     Shiva   13
9   Saurabh   20

In [ ]:
df.loc[4, 'Name']='John'
df.loc[4, 'Age']=56
print(df)

       Name  Age
0      Siva   10
1     Kamal   13
2    Akshat   21
3    Gunjan   31
4      John   56
5   Maniram   22
6  Narendra   25
7    Lokesh   12
8     Shiva   13
9   Saurabh   20

In [ ]:
df=df.drop(index=0).reset_index(drop=True)
print(df)

       Name  Age
0     Kamal   13
1    Akshat   21
2    Gunjan   31
3      John   56
4   Maniram   22
5  Narendra   25
6    Lokesh   12
7     Shiva   13
8   Saurabh   20

7. Create two separate Data Frames A and B, and perform the following operations on them:
- Concatenate the 2 dataframes to a new dataframe C
- Split the dataframe C row wise

8. Create a Data Frame with columns Name and Age. Perform the following operations.
- Write a sample code to search for name/names where age is 20
- Sort the Dataframe in ascending order of ages
- Using python loops, print the ages from the dataframe and store it in a set.