<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/My_Live_Handson/Machine_Learning/Random_forest_handson_by_me_Continuation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# step 1:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
churn_data= pd.read_csv('/content/customer_churn (1) (2).csv')

In [8]:
churn_data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [9]:
churn_data.shape

(7043, 21)

In [10]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [11]:
churn_data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
churn_data.isnull().sum().sum()

np.int64(0)

In [13]:
# monthlycharges -
churn_data['MonthlyCharges'].value_counts()

MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
56.85      1
101.70     1
48.40      1
108.35     1
72.00      1
Name: count, Length: 1585, dtype: int64

In [14]:
churn_data['TotalCharges'].value_counts()

TotalCharges
           11
20.2       11
19.75       9
20.05       8
19.9        8
           ..
130.15      1
3211.9      1
7843.55     1
2196.3      1
197.4       1
Name: count, Length: 6531, dtype: int64

In [15]:
# convert it into null nd then remove it
churn_data['TotalCharges'] = pd.to_numeric(churn_data['TotalCharges'], errors ='coerce')


# error =corece -? any invaliad values will be converted into nan(null)

# if youhave categorcal -

In [16]:
churn_data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [17]:
churn_data['TotalCharges'].value_counts() #null value not shown

TotalCharges
20.20      11
19.75       9
19.65       8
19.90       8
20.05       8
           ..
130.15      1
3211.90     1
7843.55     1
2196.30     1
197.40      1
Name: count, Length: 6530, dtype: int64

In [18]:
churn_data.drop(columns =['customerID'], inplace = True)

In [19]:
# step 1:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()

In [21]:
# step 3:
col_list = []

for i in churn_data.columns:
  if ((churn_data[i].dtypes =='object')& (i != 'Churn')): #exclude target
    col_list.append(i)

In [22]:
col_list

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [23]:
for i in col_list:
  churn_data[i] = le.fit_transform(churn_data[i])

In [24]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   int64
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   int64
 3   Dependents        7043 non-null   int64
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   int64
 6   MultipleLines     7043 non-null   int64
 7   InternetService   7043 non-null   int64
 8   OnlineSecurity    7043 non-null   int64
 9   OnlineBackup      7043 non-null   int64
 10  DeviceProtection  7043 non-null   int64
 11  TechSupport       7043 non-null   int64
 12  StreamingTV       7043 non-null   int64
 13  StreamingMovies   7043 non-null   int64
 14  Contract          7043 non-null   int64
 15  PaperlessBilling  7043 non-null   int64
 16  PaymentMethod     7043 non-null   int64
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7043 non-null   object
dtypes: float64(2), int64(17), object(1)
memory usage: 1.1+ MB

In [25]:
churn_data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,No
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,No
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,Yes
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,No
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50,No
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90,No
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45,No
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60,Yes
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50,No

In [26]:
churn_data.isnull().sum().sum()

np.int64(11)

In [33]:
churn_data=churn_data.dropna()

In [34]:
churn_data.isnull().sum().sum()

np.int64(0)

In [36]:
# dividing into independent and dependent

X = churn_data.iloc[: , :-1] # independent columns
#[ row index: row , column: column index]
y = churn_data['Churn']

In [37]:
# splitting the data into train, test

from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42,stratify=y)

# stratify means keep the same proportion of classes in both the training and testing data

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
# grid cv:

# step1
from sklearn.model_selection import GridSearchCV

In [28]:
# step2
param_grid ={
    'n_estimators': [100,200, 300],
    'max_depth': [None,5,10],
    'min_samples_leaf':[1,2, 4],
    'criterion': ['gini', 'entropy'],
    'bootstrap': [True, False]
}

In [39]:
 #step3
classifier1 = RandomForestClassifier(random_state = 42)

In [40]:
grid_search = GridSearchCV(estimator= classifier1, param_grid = param_grid, cv = 2)

In [41]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=2, estimator=RandomForestClassifier(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'n_estimators': [100, 200, 300]})

In [42]:
grid_search.best_params_

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': 5,
 'min_samples_leaf': 2,
 'n_estimators': 300}

In [43]:
classfier3 = RandomForestClassifier(n_estimators= 300, criterion='gini',max_depth=5, min_samples_leaf= 2,bootstrap=True, random_state=50)

In [44]:
classfier3.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, n_estimators=300,
                       random_state=50)

In [45]:
y_pred1 = classfier3.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score

In [48]:
accuracy_score(y_pred1, y_test)

0.7846481876332623

In [49]:
#oob (out of bag)
#  it is way to chcek the performance of the random forest model without using  a separate validation test

y = churn_data['Churn']
X1 = churn_data.iloc[:, :-1]

In [52]:
X.equals(X1)

True

In [53]:
oobclassfier = RandomForestClassifier(n_estimators = 800, oob_score = True, random_state =42)

In [54]:

oobclassfier.fit(X1, y)

RandomForestClassifier(n_estimators=800, oob_score=True, random_state=42)

In [55]:
oob_data_indices = np.where(oobclassfier.oob_decision_function_[:,1]>= 0.5)

In [56]:
oobclassfier.oob_decision_function_

array([[0.32907348, 0.67092652],
       [0.98972603, 0.01027397],
       [0.51736111, 0.48263889],
       ...,
       [0.77972028, 0.22027972],
       [0.2541806 , 0.7458194 ],
       [0.75932203, 0.24067797]])

In [57]:
oob_probs = pd.DataFrame(
    oobclassfier.oob_decision_function_,
    columns=oobclassfier.classes_
)

print(oob_probs.head(10))

         No       Yes
0  0.329073  0.670927
1  0.989726  0.010274
2  0.517361  0.482639
3  0.954064  0.045936
4  0.275510  0.724490
5  0.054054  0.945946
6  0.525180  0.474820
7  0.821549  0.178451
8  0.295681  0.704319
9  0.948980  0.051020

In [58]:
oob_probs

            No       Yes
0     0.329073  0.670927
1     0.989726  0.010274
2     0.517361  0.482639
3     0.954064  0.045936
4     0.275510  0.724490
...        ...       ...
7027  0.886288  0.113712
7028  0.778571  0.221429
7029  0.779720  0.220280
7030  0.254181  0.745819
7031  0.759322  0.240678

[7032 rows x 2 columns]