<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/My_Live_Handson/Modules/Case_Study/US_Honey_Case_Study_by_me(17th_June).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/US_honey_dataset (1).csv')
# /content/US_honey_dataset (1).csv

In [ ]:
df

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.00,575000,1995
1,1,Arizona,52000,79,4108000,986000,68.00,2793000,1995
2,2,Arkansas,50000,60,3000000,900000,64.00,1920000,1995
3,3,California,420000,93,39060000,4687000,60.00,23436000,1995
4,4,Colorado,45000,60,2700000,1404000,68.00,1836000,1995
...,...,...,...,...,...,...,...,...,...
1110,1110,Virginia,6000,40,79000,79000,8.23,1975000,2021
1111,1111,Washington,96000,32,1206000,1206000,2.52,7741000,2021
1112,1112,WestVirginia,6000,43,136000,136000,4.80,1238000,2021
1113,1113,Wisconsin,42000,47,750000,750000,2.81,5547000,2021
1114,1114,Wyoming,38000,58,242000,242000,2.07,4562000,2021

In [ ]:
df.info() #Summary of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1115 non-null   int64
 1   state                1115 non-null   object
 2   colonies_number      1115 non-null   int64
 3   yield_per_colony     1115 non-null   int64
 4   production           1115 non-null   int64
 5   stocks               1115 non-null   int64
 6   average_price        1115 non-null   float64
 7   value_of_production  1115 non-null   int64
 8   year                 1115 non-null   int64
dtypes: float64(1), int64(7), object(1)
memory usage: 78.5+ KB

In [ ]:
df.drop("Unnamed: 0", axis=1,inplace=True) #inplace: permanent changes
df

,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,Alabama,16000,58,928000,28000,62.00,575000,1995
1,Arizona,52000,79,4108000,986000,68.00,2793000,1995
2,Arkansas,50000,60,3000000,900000,64.00,1920000,1995
3,California,420000,93,39060000,4687000,60.00,23436000,1995
4,Colorado,45000,60,2700000,1404000,68.00,1836000,1995
...,...,...,...,...,...,...,...,...
1110,Virginia,6000,40,79000,79000,8.23,1975000,2021
1111,Washington,96000,32,1206000,1206000,2.52,7741000,2021
1112,WestVirginia,6000,43,136000,136000,4.80,1238000,2021
1113,Wisconsin,42000,47,750000,750000,2.81,5547000,2021
1114,Wyoming,38000,58,242000,242000,2.07,4562000,2021

In [ ]:
df.isnull().sum()

state                  0
colonies_number        0
yield_per_colony       0
production             0
stocks                 0
average_price          0
value_of_production    0
year                   0
dtype: int64

In [ ]:
#let's pretend we had null values
#df.dropna(inplace=True)

In [ ]:
cont = df.groupby(["state"])["production"].sum().reset_index()

In [ ]:
cont

            state  production
0         Alabama    14467000
1         Arizona    38844000
2        Arkansas    51846000
3      California   423876000
4        Colorado    32660000
5         Florida   280934000
6         Georgia    57426000
7          Hawaii    15420000
8           Idaho    87188000
9        Illinois     9864000
10        Indiana     9686000
11           Iowa    48607000
12         Kansas    14138000
13       Kentucky     3224000
14      Louisiana    60568000
15          Maine     4762000
16       Maryland     1975000
17       Michigan   101063000
18      Minnesota   176581000
19    Mississippi    21235000
20       Missouri    17904000
21        Montana   197173000
22       Nebraska    63655000
23         Nevada     7399000
24      NewJersey     6913000
25      NewMexico    10082000
26        NewYork    78444000
27  NorthCarolina     8909000
28    NorthDakota   513742000
29           Ohio    22485000
30       Oklahoma     2055000
31         Oregon    43789000
32   Pennsylvania    21370000
33  SouthCarolina     2823000
34    SouthDakota   355726000
35      Tennessee     6857000
36          Texas   129441000
37           Utah    20369000
38        Vermont     7032000
39       Virginia     5153000
40     Washington    53238000
41   WestVirginia     6411000
42      Wisconsin    99909000
43        Wyoming    43921000

In [ ]:
#RarCont=cont.sort_values(by="production", ascending=True).head()

RarCont=cont.sort_values(by='production', ascending=True).head()

In [ ]:
RarCont=cont.sort_values(by='production', ascending=True).head()
RarCont

            state  production
16       Maryland     1975000
30       Oklahoma     2055000
33  SouthCarolina     2823000
13       Kentucky     3224000
15          Maine     4762000

In [ ]:
topP=df.groupby(["state"])["production"].sum()

In [ ]:
topP.idxmin()

'Maryland'

In [ ]:
topP.sort_values(by ="production", asc)

AttributeError: 'int' object has no attribute 'index'

In [ ]:
topPP=df.groupby(["state"])[["production", "stocks"]].sum()

In [ ]:
topPP

               production     stocks
state
Alabama          14467000    2987000
Arizona          38844000   17758000
Arkansas         51846000   20897000
California      423876000  137611000
Colorado         32660000   18695000
Florida         280934000   47037000
Georgia          57426000    9932000
Hawaii           15420000    3508000
Idaho            87188000   40503000
Illinois          9864000    4957000
Indiana           9686000    5286000
Iowa             48607000   29351000
Kansas           14138000    7520000
Kentucky          3224000    1128000
Louisiana        60568000   12688000
Maine             4762000    2271000
Maryland          1975000     477000
Michigan        101063000   58401000
Minnesota       176581000   51908000
Mississippi      21235000    6799000
Missouri         17904000    4870000
Montana         197173000   91240000
Nebraska         63655000   38937000
Nevada            7399000    1935000
NewJersey         6913000    3311000
NewMexico        10082000    4561000
NewYork          78444000   42535000
NorthCarolina     8909000    3101000
NorthDakota     513742000  206707000
Ohio             22485000   13269000
Oklahoma          2055000     693000
Oregon           43789000   28655000
Pennsylvania     21370000   11339000
SouthCarolina     2823000     486000
SouthDakota     355726000  218634000
Tennessee         6857000    2460000
Texas           129441000   41022000
Utah             20369000    6775000
Vermont           7032000    3489000
Virginia          5153000    1809000
Washington       53238000   28500000
WestVirginia      6411000    3034000
Wisconsin        99909000   59166000
Wyoming          43921000   11235000