<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Assignments/Assignment_Quiz/Pandas_Quiz_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This dataset contains these columns: id, date, price, bedrooms, bathrooms, sqft_living,
sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built,
yr_renovated, zip code, lat, long, sqft_living15, sqft_lot15.

In [210]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [211]:
df = pd.read_csv('/content/housing.csv')

In [212]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [214]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

1) Which zip code has the costliest house?
- 89034
- 98102
- 98283
- 98456

In [215]:
df["price"].idxmax()

7252

In [216]:
costliest_house = df.loc[df["price"].idxmax()]

In [217]:
costliest_house

id                    6762700020
date             20141013T000000
price                    7700000
bedrooms                       6
bathrooms                    8.0
sqft_living                12050
sqft_lot                   27600
floors                       2.5
waterfront                     0
view                           3
condition                      4
grade                         13
sqft_above                  8570
sqft_basement               3480
yr_built                    1910
yr_renovated                1987
zipcode                    98102
lat                      47.6298
long                    -122.323
sqft_living15               3940
sqft_lot15                  8800
Name: 7252, dtype: object

In [218]:
costliest_house['zipcode']

np.int64(98102)

1. Answer - 98102

2) How many houses are having grade 10?
- 1132
- 1133
- 1135
- 1134

In [219]:
df['grade'].unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1])

In [220]:
df.loc[df['grade']==10]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
66,3394100030,20140909T000000,975000,4,2.50,2720,11049,2.0,0,0,...,10,2720,0,1989,0,98004,47.5815,-122.192,2750,11049
75,3276920270,20141105T000000,832500,4,4.00,3430,35102,2.0,0,0,...,10,2390,1040,1986,0,98075,47.5822,-121.987,3240,35020
79,1531000030,20150323T000000,720000,4,2.50,3450,39683,2.0,0,0,...,10,3450,0,2002,0,98010,47.3420,-122.025,3350,39750
91,5036300431,20150311T000000,1099880,5,2.75,3520,6353,2.0,0,0,...,10,3520,0,2001,0,98199,47.6506,-122.391,2520,6250
108,1853000400,20150305T000000,680000,4,2.50,3140,28037,2.0,0,0,...,10,3140,0,1991,0,98077,47.7304,-122.082,2990,35001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21568,524059330,20150130T000000,1700000,4,3.50,3830,8963,2.0,0,0,...,10,3120,710,2014,0,98004,47.5990,-122.197,2190,10777
21573,8562790760,20140520T000000,785000,4,3.50,3070,4684,2.0,0,0,...,10,2190,880,2009,0,98027,47.5316,-122.076,2290,2664
21576,9253900271,20150107T000000,3567000,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
21593,8672200110,20150317T000000,1088000,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21597,191100405,20150421T000000,1575000,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125

In [221]:
df.loc[df['grade']==10].count()

id               1134
date             1134
price            1134
bedrooms         1134
bathrooms        1134
sqft_living      1134
sqft_lot         1134
floors           1134
waterfront       1134
view             1134
condition        1134
grade            1134
sqft_above       1134
sqft_basement    1134
yr_built         1134
yr_renovated     1134
zipcode          1134
lat              1134
long             1134
sqft_living15    1134
sqft_lot15       1134
dtype: int64

In [222]:
df["grade"].value_counts().get(10, 0)

np.int64(1134)

In [223]:
(df["grade"] == 10).sum()

np.int64(1134)

2. Answer - 1134

3) How many null values are there in the dataset?
- 4
- 0
- 19
- 20

In [224]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [225]:
df.isnull().sum().sum()

np.int64(0)

3. Answer - 0

4) Does this 9126100861 customer have a waterfront?
- Yes
- No

In [226]:
df[df['id']==9126100861]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
400,9126100861,20150306T000000,557000,3,3.5,1710,2096,2.0,0,0,...,8,1290,420,2008,0,98122,47.6055,-122.305,1630,1543

In [227]:
df.loc[df['id']==9126100861]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
400,9126100861,20150306T000000,557000,3,3.5,1710,2096,2.0,0,0,...,8,1290,420,2008,0,98122,47.6055,-122.305,1630,1543

In [228]:
df[df['id']==9126100861]['waterfront']

400    0
Name: waterfront, dtype: int64

In [229]:
df.loc[df['id']==9126100861, 'waterfront']

400    0
Name: waterfront, dtype: int64

4. Answer - No

5) How many houses have 3 views?
- 510
- 90
- 550
- 340

In [230]:
df['view'].unique()

array([0, 3, 4, 2, 1])

In [231]:
(df['view']==3).sum()

np.int64(510)

5. Answer - 510

6) What is the lowest price of the house?
- 25000
- 45000
- 28000
- 75000

In [232]:
df['price'].min()

75000

6. Answer - 75000

7) Which area has the biggest sqft_living?
- 98055
- 98035
- None of the above
- 98053

In [233]:
df.loc[df['sqft_living']==df['sqft_living'].max(), 'zipcode']

12777    98053
Name: zipcode, dtype: int64

In [234]:
df.loc[df['sqft_living'].idxmax(), 'zipcode']

np.int64(98053)

7. Answer - 98053

8) Which of the following is having a one-dimensional array?
- None of the above
- DataFrame data type
- Series data type
- Both of the above

8. Answer - Series data type

9) What value will you get on the left side after printing a series format data?
- All of the Above
- Value
- Data
- Index

In [359]:
# Example:

S1 = pd.Series(['One', 'two', 'three'])

In [360]:
S1

0      One
1      two
2    three
dtype: object

In [361]:
print(S1)

0      One
1      two
2    three
dtype: object

9. Answer - Index

10) In what format the keys will get converted into when we convert the dictionary data into data frame format?
- Column
- Records
- Rows
- Indexes

In [362]:
# Keys in dict converted as column names

dict11 = {'Name' : ['A', 'B', 'C'],
          'Age' : [19, 20, 14]}

In [363]:
pd.DataFrame(dict11)

  Name  Age
0    A   19
1    B   20
2    C   14

10. Answer - Column

11) Write a function to perform the following operation: Increase the grade of the house by 1 if the sqft of the house is greater than 0 and less than equal to 400. If the total sqft of the house is greater than 400, increase the grade of the house by 2. After creating the above function, which syntax will be using when using apply function to run the above created function in the dataset?
- data.app(data)
- None of the above
- data.apply(your_function_name(arg1))
- data.apply_fun(function_name())

In [235]:
def update_grade(row):
    if 0 < row['sqft_living'] <= 400:
        row['grade'] += 1
    elif row['sqft_living'] > 400:
        row['grade'] += 2
    return row

In [236]:
df.apply(update_grade, axis=1)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,9,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,9,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,8,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,9,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,10,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,10,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,10,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,9,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,10,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,9,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

11. Answer - None of the above (because default axis is 0 which means columns)

12) How to check the duplicate values on id,grade and location?
- df.duplicate(subset=['id','zipcode','grade'])
- Both A & C
- df[df.duplicated(['id','zipcode','grade’])]
- df.duplicated(subset=['id','zipcode','grade'])

In [238]:
df.duplicate(subset=['id','zipcode','grade'])

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [367]:
df[df.duplicated(['id','zipcode','grade'])]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
94,6021501535,20141223T000000,700000,3,1.50,1580,5000,1.0,0,0,...,8,1290,290,1939,0,98117,47.6870,-122.386,1570,4500
314,4139480200,20141209T000000,1400000,4,3.25,4290,12103,1.0,0,3,...,11,2690,1600,1997,0,98006,47.5503,-122.102,3860,11244
325,7520000520,20150311T000000,240500,2,1.00,1240,12092,1.0,0,0,...,6,960,280,1922,1984,98146,47.4957,-122.352,1820,7460
346,3969300030,20141229T000000,239900,4,1.00,1000,7134,1.0,0,0,...,6,1000,0,1943,0,98178,47.4897,-122.240,1020,7138
372,2231500030,20150324T000000,530000,4,2.25,2180,10754,1.0,0,0,...,7,1100,1080,1954,0,98133,47.7711,-122.341,1810,6929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20181,7853400250,20150219T000000,645000,4,3.50,2910,5260,2.0,0,0,...,9,2910,0,2012,0,98065,47.5168,-121.883,2910,5260
20613,2724049222,20141201T000000,220000,2,2.50,1000,1092,2.0,0,0,...,7,990,10,2004,0,98118,47.5419,-122.271,1330,1466
20670,8564860270,20150330T000000,502000,4,2.50,2680,5539,2.0,0,0,...,8,2680,0,2013,0,98045,47.4759,-121.734,2680,5992
20780,6300000226,20150504T000000,380000,4,1.00,1200,2171,1.5,0,0,...,7,1200,0,1933,0,98133,47.7076,-122.342,1130,1598
21581,7853420110,20150504T000000,625000,3,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000

In [240]:
df.duplicated(subset=['id','zipcode','grade'])

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Length: 21613, dtype: bool

In [241]:
df.duplicated(subset=['id','zipcode','grade']).sum()

np.int64(177)

df[df.duplicated(['id','zipcode','grade'])]

df.duplicated(subset=['id','zipcode','grade'])

12. Answer - Both A and C

13) Which of the following syntax will display the last two records of df? import pandas as pd df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])
- df.loc['r2':'r3']
- df.iloc['r2':'r3']
- df.loc[:'r3']
- df.iloc[:'r3']

In [242]:
import pandas as pd
df1 = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])

In [243]:
df1

     A   B
r1  34  12
r2  78  67
r3  54  43

In [244]:
df1.loc['r2':'r3']

     A   B
r2  78  67
r3  54  43

In [245]:
df1.iloc['r2':'r3']

TypeError: cannot do positional indexing on Index with these indexers [r2] of type str

In [246]:
df1.loc[:'r3']

     A   B
r1  34  12
r2  78  67
r3  54  43

In [247]:
df1.iloc[:'r3']

TypeError: cannot do positional indexing on Index with these indexers [r3] of type str

13. Answer - df.loc['r2':'r3']

14) Which of the following is/are true about loc in pandas:
- Add new rows in the data frames
- All of the above
- To extract values from the particular rows
- To change the values of a row to a particular value

In [248]:
df.loc[5]      # extract row with index label 5
df.loc[2:4]    # extract rows with labels 2,3,4

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000,2,1.0,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.0,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.0,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [262]:
df_copy = df.copy()

In [263]:
df_copy.loc[5, "price"] = 999999  # change value

In [264]:
df.loc[5, 'price']

np.int64(1225000)

In [265]:
df_copy.loc[5, 'price']

np.int64(999999)

In [266]:
length = len(df_copy)

# Add new row at the end using length as index using loc
df_copy.loc[length] = df_copy.loc[5]

14. Answer - All the above

15) Which of the following is the correct syntax for getting the houses where no. of bedrooms is maximum having 3 views along with 1 waterfront?
- housing[(housing["bedrooms"]==housing["bedrooms"].mean()) & (housing["view"]==3) & (housing["waterfront"]==1)]
- housing[(housing["bedrooms"]==2) & (housing["view"]==3) & (housing["waterfront"]==1)]
- housing[(housing["bedrooms"]==housing["bedrooms"].max()) & (housing["view"]==3) & (housing["waterfront"]==1)]
- None of the Above

In [268]:
housing = df.copy()

In [273]:
# mean does not find maximum bedrooms
housing[(housing["bedrooms"]==housing["bedrooms"].mean()) & (housing["view"]==3) & (housing["waterfront"]==1)]

Empty DataFrame
Columns: [id, date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

[0 rows x 21 columns]

In [276]:
housing['bedrooms'].max()

33

In [274]:
# max bedrooms is not 2
housing[(housing["bedrooms"]==2) & (housing["view"]==3) & (housing["waterfront"]==1)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1168,3523029041,20141009T000000,290000,2,0.75,440,8313,1.0,1,3,...,5,440,0,1943,0,98070,47.4339,-122.512,880,26289
2339,1724069062,20140714T000000,1365000,2,3.25,2700,3444,3.0,1,3,...,9,2700,0,1990,0,98075,47.5684,-122.060,2710,3444
8163,1724069079,20150319T000000,1452000,2,3.25,2070,3128,2.0,1,3,...,9,1760,310,1988,0,98075,47.5686,-122.060,2740,3568
8978,1724069060,20150507T000000,1075000,2,3.25,1550,1767,3.0,1,3,...,8,1550,0,2006,0,98075,47.5684,-122.060,2710,3444
19002,5216200090,20140616T000000,385000,2,1.00,830,26329,1.0,1,3,...,6,830,0,1928,0,98070,47.4012,-122.425,2030,27338
19104,594000115,20140512T000000,615000,2,1.75,2040,28593,1.5,1,3,...,7,2040,0,1919,1990,98070,47.3979,-122.465,2040,35124

In [275]:
# max finds maximum bedrooms - this is correct
housing[(housing["bedrooms"]==housing["bedrooms"].max()) & (housing["view"]==3) & (housing["waterfront"]==1)]

Empty DataFrame
Columns: [id, date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

[0 rows x 21 columns]

15. Answer - housing[(housing["bedrooms"]==housing["bedrooms"].max()) & (housing["view"]==3) & (housing["waterfront"]==1)]

16) Create a separate data frame that satisfies the conditions below. 1. Houses built before 1980 2. Have more than 2 bedrooms 3. Have more than 2 floors.
- data.loc[(data["yr_built"] > 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]
- data.loc[(data["yr_built"] | 1980) & (data['floors'] > 2) | (data['bedrooms'] > 2)]
- data.loc[(data["yr_built"] < 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]
- data.loc[(data["yr_built"] < 1980) | (data['floors'] > 2) | (data['bedrooms'] < 2)]

In [278]:
data = df.copy()

In [279]:
data.loc[(data["yr_built"] > 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]

# year > 1980 means after 1980 not before 1980

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
63,9528102996,20141207T000000,549000,3,1.75,1540,1044,3.0,0,0,...,8,1540,0,2014,0,98115,47.6765,-122.320,1580,3090
116,3362400431,20140626T000000,518500,3,3.50,1590,1102,3.0,0,0,...,8,1590,0,2010,0,98103,47.6824,-122.347,1620,3166
134,2767602356,20150126T000000,675000,4,3.50,2140,2278,3.0,0,0,...,9,2140,0,2005,0,98107,47.6734,-122.380,1540,2285
139,2767603505,20140507T000000,519950,3,2.25,1170,1249,3.0,0,0,...,8,1170,0,2014,0,98107,47.6722,-122.381,1350,1310
406,7821200390,20140806T000000,450000,3,2.00,1290,1213,3.0,0,0,...,8,1290,0,2001,0,98103,47.6609,-122.344,1290,3235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21587,6632300207,20150305T000000,385000,3,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21592,1931300412,20150416T000000,475000,3,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21601,5100403806,20150407T000000,467000,3,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21604,9834201367,20150126T000000,429000,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509

In [283]:
data.loc[(data["yr_built"] | 1980) & (data['floors'] > 2) | (data['bedrooms'] > 2)]

# or | means any one condition, not all 3 condition
# all the & | are bitwise because row wise we are going to use in series or df"
# (data["yr_built"] | 1980) always True

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21606,7936000429,20150326T000000,1007500,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287

In [281]:
data.loc[(data["yr_built"] < 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]

# this satisfies all 3 given condition as & is used - correct answer

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
518,4386700135,20141114T000000,2250000,4,2.25,4760,8036,2.5,0,0,...,9,3390,1370,1916,0,98112,47.6415,-122.285,2950,9323
759,770000045,20141024T000000,405600,5,1.50,2830,4000,2.5,0,0,...,8,2830,0,1918,0,98118,47.5132,-122.262,1480,4000
960,7578200310,20141112T000000,650000,4,2.00,2208,5000,3.0,0,0,...,8,2208,0,1917,0,98116,47.5711,-122.383,1760,5000
1296,5458800125,20140514T000000,925000,4,2.50,2190,7350,2.5,0,0,...,8,2190,0,1958,0,98040,47.5786,-122.236,1880,7350
1350,7234600786,20140511T000000,842500,4,2.50,2160,5298,2.5,0,0,...,9,2160,0,1902,0,98122,47.6106,-122.310,1720,2283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18535,3667500015,20140925T000000,770000,4,3.50,3680,2242,2.5,0,0,...,9,2670,1010,1930,2007,98112,47.6192,-122.307,1350,1288
18631,1337800665,20140811T000000,1325000,4,3.25,2850,4800,2.5,0,0,...,10,2700,150,1905,0,98112,47.6292,-122.312,2850,4800
19068,6613001241,20140811T000000,1415000,4,3.00,3110,4408,2.5,0,3,...,10,2510,600,1931,0,98105,47.6583,-122.270,3250,5669
19188,7942601475,20140520T000000,345600,5,3.50,2800,5120,2.5,0,0,...,9,2800,0,1903,2005,98122,47.6059,-122.310,1780,5120
19272,1337300145,20140721T000000,1800000,4,2.50,3320,8325,2.5,0,0,...,10,3320,0,1905,0,98112,47.6263,-122.314,3680,6050

In [ ]:
data.loc[(data["yr_built"] < 1980) | (data['floors'] > 2) | (data['bedrooms'] < 2)]
# | checks any one condition, not all conditions

In [284]:
new_df = data.loc[(data["yr_built"] < 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]

In [285]:
new_df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
518,4386700135,20141114T000000,2250000,4,2.25,4760,8036,2.5,0,0,...,9,3390,1370,1916,0,98112,47.6415,-122.285,2950,9323
759,770000045,20141024T000000,405600,5,1.50,2830,4000,2.5,0,0,...,8,2830,0,1918,0,98118,47.5132,-122.262,1480,4000
960,7578200310,20141112T000000,650000,4,2.00,2208,5000,3.0,0,0,...,8,2208,0,1917,0,98116,47.5711,-122.383,1760,5000
1296,5458800125,20140514T000000,925000,4,2.50,2190,7350,2.5,0,0,...,8,2190,0,1958,0,98040,47.5786,-122.236,1880,7350
1350,7234600786,20140511T000000,842500,4,2.50,2160,5298,2.5,0,0,...,9,2160,0,1902,0,98122,47.6106,-122.310,1720,2283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18535,3667500015,20140925T000000,770000,4,3.50,3680,2242,2.5,0,0,...,9,2670,1010,1930,2007,98112,47.6192,-122.307,1350,1288
18631,1337800665,20140811T000000,1325000,4,3.25,2850,4800,2.5,0,0,...,10,2700,150,1905,0,98112,47.6292,-122.312,2850,4800
19068,6613001241,20140811T000000,1415000,4,3.00,3110,4408,2.5,0,3,...,10,2510,600,1931,0,98105,47.6583,-122.270,3250,5669
19188,7942601475,20140520T000000,345600,5,3.50,2800,5120,2.5,0,0,...,9,2800,0,1903,2005,98122,47.6059,-122.310,1780,5120
19272,1337300145,20140721T000000,1800000,4,2.50,3320,8325,2.5,0,0,...,10,3320,0,1905,0,98112,47.6263,-122.314,3680,6050

16. Answer - data.loc[(data["yr_built"] < 1980) & (data['floors'] > 2) & (data['bedrooms'] > 2)]

17) For a given nested list, convert the same into a dataframe. sample_list = [['Carl', 22], ['Martha', 25], ['Calvin', 12], ['Stuart', 15] ] The resulting dataframe must contain the column names as ‘Name’, and ‘Age’ with the respective values from the sample_list.
- pd.DataFrame(sample_list, column_names=['Name', 'Age'])
- pd.DataFrame(sample_list, columns=['Name', 'Age'])
- pd.DataFrame(sample_list)
- pd.DataFrame(sample_list, column_name=['Name', 'Age'])

In [286]:
sample_list = [['Carl', 22], ['Martha', 25], ['Calvin', 12], ['Stuart', 15] ]

In [287]:
pd.DataFrame(sample_list, column_names=['Name', 'Age'])

TypeError: DataFrame.__init__() got an unexpected keyword argument 'column_names'

In [288]:
pd.DataFrame(sample_list, columns=['Name', 'Age'])

     Name  Age
0    Carl   22
1  Martha   25
2  Calvin   12
3  Stuart   15

In [289]:
pd.DataFrame(sample_list) # works but no column name as given

        0   1
0    Carl  22
1  Martha  25
2  Calvin  12
3  Stuart  15

In [290]:
pd.DataFrame(sample_list, column_name=['Name', 'Age'])

TypeError: DataFrame.__init__() got an unexpected keyword argument 'column_name'

17. Answer - pd.DataFrame(sample_list, columns=['Name', 'Age'])

18) For a given dictionary, convert the same into a dataframe. sample_dict = {'Cristiano': ['Ronaldo','Man U', 801], 'Lionel': ['Messi','PSG', 758], 'Luis': ['Suarez','Atletico Madrid', 509], 'Robert': ['Lewandowski','Bayern Munich', 527], 'Zlatan': ['Ibrahimovic','AC Milan',553] }
- df1 = pd.DataFrame(sample_dict) df1.reset_index(inplace = True) df1.columns = ['First Name','Last Name', 'Club', 'Goals']
- df1 = pd.DataFrame(sample_dict) df1 = df1.transpose() df1.columns = ['First Name','Last Name', 'Club', 'Goals']
- df1 = pd.Dataframe(sample_dict) df1 = df1.transpose() df1.reset_index(inplace = True) df1.columns = ['First Name','Last Name', 'Club', 'Goals']
- df1 = pd.DataFrame(sample_dict) df1 = df1.transpose() df1.reset_index(inplace = True) df1.columns = ['First Name','Last Name', 'Club', 'Goals']

In [291]:
sample_dict = {'Cristiano': ['Ronaldo','Man U', 801], 'Lionel': ['Messi','PSG', 758], 'Luis': ['Suarez','Atletico Madrid', 509], 'Robert': ['Lewandowski','Bayern Munich', 527], 'Zlatan': ['Ibrahimovic','AC Milan',553] }

{
  
  'Cristiano': ['Ronaldo','Man U', 801],

 'Lionel': ['Messi','PSG', 758],

  'Luis': ['Suarez','Atletico Madrid', 509],
  
  'Robert': ['Lewandowski','Bayern Munich', 527],
  
  'Zlatan': ['Ibrahimovic','AC Milan',553]
  
   }

In [293]:
df11 = pd.DataFrame(sample_dict)
df11.reset_index(inplace = True)
#df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

   index Cristiano Lionel             Luis         Robert       Zlatan
0      0   Ronaldo  Messi           Suarez    Lewandowski  Ibrahimovic
1      1     Man U    PSG  Atletico Madrid  Bayern Munich     AC Milan
2      2       801    758              509            527          553

In [294]:
df11 = pd.DataFrame(sample_dict)
df11.reset_index(inplace = True)
df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

ValueError: Length mismatch: Expected axis has 6 elements, new values have 4 elements

In [298]:
df11 = pd.DataFrame(sample_dict)
df11

  Cristiano Lionel             Luis         Robert       Zlatan
0   Ronaldo  Messi           Suarez    Lewandowski  Ibrahimovic
1     Man U    PSG  Atletico Madrid  Bayern Munich     AC Milan
2       801    758              509            527          553

In [297]:
df11 = pd.DataFrame(sample_dict)
df11 = df11.transpose()
#df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

                     0                1    2
Cristiano      Ronaldo            Man U  801
Lionel           Messi              PSG  758
Luis            Suarez  Atletico Madrid  509
Robert     Lewandowski    Bayern Munich  527
Zlatan     Ibrahimovic         AC Milan  553

In [300]:
df11 = pd.DataFrame(sample_dict)
df11 = df11.transpose()
df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

# error because 1st name is index here not a column

ValueError: Length mismatch: Expected axis has 3 elements, new values have 4 elements

In [301]:
df11 = pd.Dataframe(sample_dict) # F should be there
df11 = df11.transpose()
df11.reset_index(inplace = True)
df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [303]:
df11 = pd.DataFrame(sample_dict)
df11 = df11.transpose()
df11.reset_index(inplace = True)
df11.columns = ['First Name','Last Name', 'Club', 'Goals']
df11

  First Name    Last Name             Club Goals
0  Cristiano      Ronaldo            Man U   801
1     Lionel        Messi              PSG   758
2       Luis       Suarez  Atletico Madrid   509
3     Robert  Lewandowski    Bayern Munich   527
4     Zlatan  Ibrahimovic         AC Milan   553

18. Answer - df1 = pd.DataFrame(sample_dict) df1 = df1.transpose() df1.reset_index(inplace = True) df1.columns = ['First Name','Last Name', 'Club', 'Goals']

19) For a given tuple, convert the same into a dataframe. sample_tuple = ([1, 'one', 3], [2, 'two', 3], [3, 'Three', 5], [4, 'Four', 4], [5, 'Five', 4])
- pd.dataframe(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])
- pd.DataFrame(sample_tup, columns=['Number', 'Number_text', 'txtlen'])
- pd.Dataframe(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])
- pd.DataFrame(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])

In [304]:
sample_tuple = ([1, 'one', 3], [2, 'two', 3], [3, 'Three', 5], [4, 'Four', 4], [5, 'Five', 4])

In [305]:
pd.dataframe(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])

AttributeError: module 'pandas' has no attribute 'dataframe'

In [306]:
pd.DataFrame(sample_tup, columns=['Number', 'Number_text', 'txtlen'])

NameError: name 'sample_tup' is not defined

In [307]:
pd.Dataframe(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [308]:
pd.DataFrame(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])

   Number Number_text  txtlen
0       1         one       3
1       2         two       3
2       3       Three       5
3       4        Four       4
4       5        Five       4

Except last one others have spelling mistake

19. Answer - pd.DataFrame(sample_tuple, columns=['Number', 'Number_text', 'txtlen'])

20) Create a separate dataframe that contains houses ordered in ascending or descending order of the prices of each house.
- ascending = housing.sort_values('price', ascending=True) descending = housing.sort_values('price', ascending=True)
- ascending = housing.sort_values('price', ascending=False) descending = housing.sort_values('price', ascending=False)
- ascending = housing.sort_values('price', ascending=False) descending = housing.sort_values('price', ascending=True)
- ascending = housing.sort_values('price', ascending=True) descending = housing.sort_values('price', ascending=False)

In [309]:
housing.sort_values('price')

# sort_values sort the dataframe according to given column
# ascending should be true for ascending and false for descending, default it is ascending true

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882
15293,40000362,20140506T000000,78000,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
465,8658300340,20140523T000000,80000,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
16198,3028200080,20150324T000000,81000,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
8274,3883800011,20141105T000000,82000,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,8907500070,20150413T000000,5350000,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
4411,2470100110,20140804T000000,5570000,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
9254,9208900037,20140919T000000,6885000,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
3914,9808700762,20140611T000000,7062500,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
7252,6762700020,20141013T000000,7700000,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [310]:
# last option is correct
ascending = housing.sort_values('price', ascending=True)
ascending

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882
15293,40000362,20140506T000000,78000,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
465,8658300340,20140523T000000,80000,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
16198,3028200080,20150324T000000,81000,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
8274,3883800011,20141105T000000,82000,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,8907500070,20150413T000000,5350000,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
4411,2470100110,20140804T000000,5570000,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
9254,9208900037,20140919T000000,6885000,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
3914,9808700762,20140611T000000,7062500,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
7252,6762700020,20141013T000000,7700000,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [311]:
descending = housing.sort_values('price', ascending=False)
descending

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
3914,9808700762,20140611T000000,7062500,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
9254,9208900037,20140919T000000,6885000,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
4411,2470100110,20140804T000000,5570000,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
1448,8907500070,20150413T000000,5350000,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8274,3883800011,20141105T000000,82000,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
16198,3028200080,20150324T000000,81000,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
465,8658300340,20140523T000000,80000,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
15293,40000362,20140506T000000,78000,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
1149,3421079032,20150217T000000,75000,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882

20. Answer - ascending = housing.sort_values('price', ascending=True) descending = housing.sort_values('price', ascending=False)

21) Calculate the mean and standard deviation of all the numerical values in the dataset. For example - the mean for the bedrooms column is 3.370 and the standard deviation is 0.930.
- housing.corr()
- housing.std()
- housing.describe()
- housing.info()

In [312]:
housing.corr() # gives correlation matrix

ValueError: could not convert string to float: '20141013T000000'

In [313]:
housing.std() # gives only standard deviation

TypeError: could not convert string to float: '20141013T000000'

In [314]:
housing.describe() # gives statistical details including means ans standard deviation of all numerical columns

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [315]:
housing.info() # gives column wise info as type and number of rows non null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

21. Answer - housing.describe()

22) Create a new column with the floor area(sqft_living, sqft_lot, sqft_above, sqft_basement, all combined in one column).
- data['Floor Area'] = data['sqft_living'], data['sqft_lot'], data['sqft_basement'], data['sqft_above']
- data['Floor Area'] = data['sqft_living', 'sqft_lot','sqft_basement','sqft_above']
- df['Floor Area'] = data['sqft_living'] + data['sqft_lot'] + data['sqft_basement'] + data['sqft_above']
- data['Floor Area'] = data['sqft_liv', 'sqft_lot','sqft_base','sqft_above']

In [316]:
data['Floor Area'] = data['sqft_living'], data['sqft_lot'], data['sqft_basement'], data['sqft_above']

ValueError: Length of values (4) does not match length of index (21613)

In [364]:
(data['sqft_living'], data['sqft_lot'], data['sqft_basement'], data['sqft_above'])

(0        1180
 1        2570
 2         770
 3        1960
 4        1680
          ...
 21608    1530
 21609    2310
 21610    1020
 21611    1600
 21612    1020
 Name: sqft_living, Length: 21613, dtype: int64,
 0         5650
 1         7242
 2        10000
 3         5000
 4         8080
          ...
 21608     1131
 21609     5813
 21610     1350
 21611     2388
 21612     1076
 Name: sqft_lot, Length: 21613, dtype: int64,
 0          0
 1        400
 2          0
 3        910
 4          0
         ...
 21608      0
 21609      0
 21610      0
 21611      0
 21612      0
 Name: sqft_basement, Length: 21613, dtype: int64,
 0        1180
 1        2170
 2         770
 3        1050
 4        1680
          ...
 21608    1530
 21609    2310
 21610    1020
 21611    1600
 21612    1020
 Name: sqft_above, Length: 21613, dtype: int64)

In [320]:
(data['sqft_living'], data['sqft_lot'], data['sqft_basement'], data['sqft_above'])[0]

0        1180
1        2570
2         770
3        1960
4        1680
         ...
21608    1530
21609    2310
21610    1020
21611    1600
21612    1020
Name: sqft_living, Length: 21613, dtype: int64

In [324]:
data['Floor Area'] = data['sqft_living', 'sqft_lot','sqft_basement','sqft_above']

KeyError: ('sqft_living', 'sqft_lot', 'sqft_basement', 'sqft_above')

In [325]:
data['sqft_living', 'sqft_lot','sqft_basement','sqft_above']  # [[]] needed

KeyError: ('sqft_living', 'sqft_lot', 'sqft_basement', 'sqft_above')

In [326]:
data['Floor Area'] = data['sqft_living'] + data['sqft_lot'] + data['sqft_basement'] + data['sqft_above']

In [327]:
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Floor Area
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,8010
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,12382
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,11540
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,8920
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,11440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,4191
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,10433
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,3390
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,5588
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,3116

In [328]:
data['Floor Area'] = data['sqft_liv', 'sqft_lot','sqft_base','sqft_above']

KeyError: ('sqft_liv', 'sqft_lot', 'sqft_base', 'sqft_above')

22. Answer - df['Floor Area'] = data['sqft_living'] + data['sqft_lot'] + data['sqft_basement'] + data['sqft_above']

23) Perform the following operations on the dataframes given below. A = pd.DataFrame([['Carl', 22],['Martha', 25],['Calvin', 12],['Stuart', 15]], columns=[‘Name’, ‘Age’]) B = pd.DataFrame([['Melvin', 25],['Martha', 34],['Lewis', 32],['Leo', 25]], columns=[‘Name’, ‘Age’]) 1. Left Outer Join 2. Outer Join 3. Inner Join 4. Right Outer Join
- inner = pd.merge(A, B, on='Age', how='inner') outer = pd.merge(A, B, on='Age', how='outer') left_outer = pd.merge(A, B, on='Age', how='left') right_outer = pd.merge(A, B, on='Age', how='right')
- inner = pd.merge(A, B, on='Age', how='inner') outer = pd.merge(A, B, on='Age', how='outer') left_outer = pd.merge(A, B, on='Age', how='left_outer')
- inner = pd.merge(A, B, on='Age', how='inner') outer = pd.merge(A, B, on='Age', how='outer') left_outer = pd.merge(A, B, on='Age', how='outer_left') right_outer = pd.merge(A, B, on='Age', how='outer_right')
- inner = pd.merge(A, B, on='Age', how='inner_join') outer = pd.merge(A, B, on='Age', how='outer_join') left_outer = pd.merge(A, B, on='Age', how='left_join') right_outer = pd.merge(A, B, on='Age', how='right_join')

In [330]:
A = pd.DataFrame([['Carl', 22],['Martha', 25],['Calvin', 12],['Stuart', 15]], columns=['Name', 'Age'])
B = pd.DataFrame([['Melvin', 25],['Martha', 34],['Lewis', 32],['Leo', 25]], columns=['Name', 'Age'])

In [332]:
A

     Name  Age
0    Carl   22
1  Martha   25
2  Calvin   12
3  Stuart   15

In [333]:
B

     Name  Age
0  Melvin   25
1  Martha   34
2   Lewis   32
3     Leo   25

Merge definition of parameters

eft : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.


left: use only keys from left frame, similar to a SQL left outer join;
preserve key order.

right: use only keys from right frame, similar to a SQL right outer join;
preserve key order.

outer: use union of keys from both frames, similar to a SQL full outer
join; sort keys lexicographically.

inner: use intersection of keys from both frames, similar to a SQL inner
join; preserve the order of the left keys.

cross: creates the cartesian product from both frames, preserves the order
of the left keys.
on : label or list

option A

In [334]:
inner = pd.merge(A, B, on='Age', how='inner')
outer = pd.merge(A, B, on='Age', how='outer')
left_outer = pd.merge(A, B, on='Age', how='left')
right_outer = pd.merge(A, B, on='Age', how='right')
print(inner)
print(outer)
print(left_outer)
print(right_outer)

   Name_x  Age  Name_y
0  Martha   25  Melvin
1  Martha   25     Leo
   Name_x  Age  Name_y
0  Calvin   12     NaN
1  Stuart   15     NaN
2    Carl   22     NaN
3  Martha   25  Melvin
4  Martha   25     Leo
5     NaN   32   Lewis
6     NaN   34  Martha
   Name_x  Age  Name_y
0    Carl   22     NaN
1  Martha   25  Melvin
2  Martha   25     Leo
3  Calvin   12     NaN
4  Stuart   15     NaN
   Name_x  Age  Name_y
0  Martha   25  Melvin
1     NaN   34  Martha
2     NaN   32   Lewis
3  Martha   25     Leo

In [335]:
inner

   Name_x  Age  Name_y
0  Martha   25  Melvin
1  Martha   25     Leo

In [336]:
outer

   Name_x  Age  Name_y
0  Calvin   12     NaN
1  Stuart   15     NaN
2    Carl   22     NaN
3  Martha   25  Melvin
4  Martha   25     Leo
5     NaN   32   Lewis
6     NaN   34  Martha

In [337]:
left_outer

   Name_x  Age  Name_y
0    Carl   22     NaN
1  Martha   25  Melvin
2  Martha   25     Leo
3  Calvin   12     NaN
4  Stuart   15     NaN

In [338]:
right_outer

   Name_x  Age  Name_y
0  Martha   25  Melvin
1     NaN   34  Martha
2     NaN   32   Lewis
3  Martha   25     Leo

Option B

In [341]:
inner = pd.merge(A, B, on='Age', how='inner')
outer = pd.merge(A, B, on='Age', how='outer')
left_outer = pd.merge(A, B, on='Age', how='left_outer')
# error because lidx ridx are never assigned , still tries to return. if elif
# left_outer is not valid value for how


# right_outer is missing

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

Option C

In [343]:
inner = pd.merge(A, B, on='Age', how='inner')
outer = pd.merge(A, B, on='Age', how='outer')
left_outer = pd.merge(A, B, on='Age', how='outer_left')
# right_outer = pd.merge(A, B, on='Age', how='outer_right')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

In [344]:
inner = pd.merge(A, B, on='Age', how='inner')
outer = pd.merge(A, B, on='Age', how='outer')
# left_outer = pd.merge(A, B, on='Age', how='outer_left')
right_outer = pd.merge(A, B, on='Age', how='outer_right')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

Option D

In [346]:
inner = pd.merge(A, B, on='Age', how='inner_join')
# outer = pd.merge(A, B, on='Age', how='outer_join')
# left_outer = pd.merge(A, B, on='Age', how='left_join')
# right_outer = pd.merge(A, B, on='Age', how='right_join')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

In [347]:
outer = pd.merge(A, B, on='Age', how='outer_join')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

In [348]:
left_outer = pd.merge(A, B, on='Age', how='left_join')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

In [349]:
right_outer = pd.merge(A, B, on='Age', how='right_join')

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

23. Answer - Option A or Option 1

inner = pd.merge(A, B, on='Age', how='inner') outer = pd.merge(A, B, on='Age', how='outer') left_outer = pd.merge(A, B, on='Age', how='left') right_outer = pd.merge(A, B, on='Age', how='right')

24) What will be the correlation between the columns sqft_living and sqft_above?
- 0.754665
- 0.303093
- 0.876597
- 0.702035

In [356]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [357]:
# we are going to use series correlation

df['sqft_living'].corr(df['sqft_above'])

np.float64(0.876596598681318)

24. Answer - 0.876597

25) If the correlation between the columns bathrooms and sqft_living is 0.754665, what all interpretations can be made about the two columns?
- A positive correlation between the two columns
- A strong negative correlation between the two columns
- The columns show perfect correlation.
- No correlation between the two columns.

In [358]:
df['bathrooms'].corr(df['sqft_living'])

np.float64(0.7546652789673731)

25. Answer - A positive correlation between the two columns