<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Assignments/Assignment_Quiz/Quiz_Logistic_regression_(live_class).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Which of the following is a characteristic of logistic regression?

* 1 point

It is used for predicting continuous outcomes.

It assumes a linear relationship between predictors and the response variable.

It uses the logistic function to model the probability of a binary outcome.

It is not suitable for handling categorical predictors.

2) Which of the following metrics is commonly used to evaluate the performance of a logistic regression model?

*

1 point

A) R-squared

B) Mean squared error (MSE)

C) F1 score

D) Root mean square error (RMSE)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Invistico_Airline.csv')

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,mean_absolute_percentage_error

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

In [ ]:
df.isnull().sum().sum()

np.int64(375)

In [ ]:
df.isnull().sum()

satisfaction                           0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  1
Flight Distance                        1
Seat comfort                           1
Departure/Arrival time convenient      1
Food and drink                         1
Gate location                          1
Inflight wifi service                  1
Inflight entertainment                 1
Online support                         1
Ease of Online booking                 1
On-board service                       1
Leg room service                       1
Baggage handling                       1
Checkin service                        1
Cleanliness                            1
Online boarding                        1
Departure Delay in Minutes             1
Arrival Delay in Minutes             358
dtype: int64

3) Compute the count of Null Values in the Mentioned Dataset?

*
1 point

562

138

242

393

4) Which  is the most preferred class of travel by passengers of invisto Airlines?


*
1 point

Business

Eco

Eco Plus

Both 1 & 3

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265.0,0.0,0.0,0.0,...,2.0,3.0,3.0,0.0,3.0,5.0,3.0,2.0,0.0,0.0
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464.0,0.0,0.0,0.0,...,2.0,3.0,4.0,4.0,4.0,2.0,3.0,2.0,310.0,305.0
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138.0,0.0,0.0,0.0,...,2.0,2.0,3.0,3.0,4.0,4.0,4.0,2.0,0.0,0.0
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623.0,0.0,0.0,0.0,...,3.0,1.0,1.0,0.0,1.0,4.0,1.0,3.0,0.0,0.0
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354.0,0.0,0.0,0.0,...,4.0,2.0,2.0,0.0,2.0,4.0,2.0,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118726,satisfied,Female,Loyal Customer,44,Business travel,Eco,590.0,5.0,5.0,5.0,...,4.0,5.0,5.0,5.0,5.0,3.0,5.0,2.0,0.0,0.0
118727,satisfied,Female,Loyal Customer,43,Business travel,Eco,1149.0,5.0,4.0,4.0,...,4.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,0.0,0.0
118728,satisfied,Female,Loyal Customer,43,Business travel,Eco Plus,720.0,5.0,1.0,1.0,...,3.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,0.0
118729,satisfied,Male,Loyal Customer,43,Business travel,Eco,2364.0,5.0,1.0,1.0,...,5.0,5.0,3.0,3.0,2.0,4.0,4.0,5.0,60.0,47.0
118730,satisfied,Male,Loyal Customer,43,Business trav,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118731 entries, 0 to 118730
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction                       118731 non-null  object
 1   Gender                             118731 non-null  object
 2   Customer Type                      118731 non-null  object
 3   Age                                118731 non-null  int64
 4   Type of Travel                     118731 non-null  object
 5   Class                              118730 non-null  object
 6   Flight Distance                    118730 non-null  float64
 7   Seat comfort                       118730 non-null  float64
 8   Departure/Arrival time convenient  118730 non-null  float64
 9   Food and drink                     118730 non-null  float64
 10  Gate location                      118730 non-null  float64
 11  Inflight wifi service              118730 non-null  float64
 12  Inflight entertainment             118730 non-null  float64
 13  Online support                     118730 non-null  float64
 14  Ease of Online booking             118730 non-null  float64
 15  On-board service                   118730 non-null  float64
 16  Leg room service                   118730 non-null  float64
 17  Baggage handling                   118730 non-null  float64
 18  Checkin service                    118730 non-null  float64
 19  Cleanliness                        118730 non-null  float64
 20  Online boarding                    118730 non-null  float64
 21  Departure Delay in Minutes         118730 non-null  float64
 22  Arrival Delay in Minutes           118373 non-null  float64
dtypes: float64(17), int64(1), object(5)
memory usage: 20.8+ MB

In [ ]:
df['Class'].unique()

array(['Eco', 'Business', 'Eco Plus', nan], dtype=object)

In [ ]:
df_no_null['Class'].value_counts()

Class
Eco         56547
Business    52881
Eco Plus     8945
Name: count, dtype: int64

In [ ]:
df['Class'].value_counts().max()

56732

5) Which of the following statements is true?

*
1 point

Organization has a larger proportion of Loyal customers than disloyal customers

Female proportion is more than male proportion

Both 1 and 2

None of the above

In [ ]:
df_no_null = df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118731 entries, 0 to 118730
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction                       118731 non-null  object
 1   Gender                             118731 non-null  object
 2   Customer Type                      118731 non-null  object
 3   Age                                118731 non-null  int64
 4   Type of Travel                     118731 non-null  object
 5   Class                              118730 non-null  object
 6   Flight Distance                    118730 non-null  float64
 7   Seat comfort                       118730 non-null  float64
 8   Departure/Arrival time convenient  118730 non-null  float64
 9   Food and drink                     118730 non-null  float64
 10  Gate location                      118730 non-null  float64
 11  Inflight wifi service              118730 non-null  float64
 12  Inflight entertainment             118730 non-null  float64
 13  Online support                     118730 non-null  float64
 14  Ease of Online booking             118730 non-null  float64
 15  On-board service                   118730 non-null  float64
 16  Leg room service                   118730 non-null  float64
 17  Baggage handling                   118730 non-null  float64
 18  Checkin service                    118730 non-null  float64
 19  Cleanliness                        118730 non-null  float64
 20  Online boarding                    118730 non-null  float64
 21  Departure Delay in Minutes         118730 non-null  float64
 22  Arrival Delay in Minutes           118373 non-null  float64
dtypes: float64(17), int64(1), object(5)
memory usage: 20.8+ MB

In [ ]:
df_no_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118373 entries, 0 to 118729
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction                       118373 non-null  object
 1   Gender                             118373 non-null  object
 2   Customer Type                      118373 non-null  object
 3   Age                                118373 non-null  int64
 4   Type of Travel                     118373 non-null  object
 5   Class                              118373 non-null  object
 6   Flight Distance                    118373 non-null  float64
 7   Seat comfort                       118373 non-null  float64
 8   Departure/Arrival time convenient  118373 non-null  float64
 9   Food and drink                     118373 non-null  float64
 10  Gate location                      118373 non-null  float64
 11  Inflight wifi service              118373 non-null  float64
 12  Inflight entertainment             118373 non-null  float64
 13  Online support                     118373 non-null  float64
 14  Ease of Online booking             118373 non-null  float64
 15  On-board service                   118373 non-null  float64
 16  Leg room service                   118373 non-null  float64
 17  Baggage handling                   118373 non-null  float64
 18  Checkin service                    118373 non-null  float64
 19  Cleanliness                        118373 non-null  float64
 20  Online boarding                    118373 non-null  float64
 21  Departure Delay in Minutes         118373 non-null  float64
 22  Arrival Delay in Minutes           118373 non-null  float64
dtypes: float64(17), int64(1), object(5)
memory usage: 21.7+ MB

In [ ]:
df['Customer Type'].value_counts()

Customer Type
Loyal Customer       95152
disloyal Customer    23579
Name: count, dtype: int64

In [ ]:
df_no_null['Customer Type'].value_counts()

Customer Type
Loyal Customer       94858
disloyal Customer    23515
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts().get('Female') > df['Gender'].value_counts().get('Male')

np.True_

In [ ]:
df_no_null['Gender'].value_counts().get('Female') > df_no_null['Gender'].value_counts().get('Male')

np.True_

In [ ]:
len(df[(df['Age'] >= 60) & (df['Class']=='Business')])

3430

In [ ]:
len(df[(df['Age'] > 60) & (df['Class']=='Business')])

2393

In [ ]:
len(df_no_null[(df_no_null['Age'] > 60) & (df_no_null['Class']=='Business')])

2385

In [ ]:
len(df_no_null[(df_no_null['Age'] >= 60) & (df_no_null['Class']=='Business')])

3418

In [ ]:
df['Gender'].value_counts().get('Female') / df['Gender'].value_counts().get('Male')

np.float64(1.0337963993901917)

In [ ]:
df_no_null['Gender'].value_counts().get('Female') / df_no_null['Gender'].value_counts().get('Male')

np.float64(1.0339702395271315)

6) What is the Number of Senior citizens(Age >60) traveling in Business class?

*
1 point

3891

2653

4000

2656

7) Compute the sex ratio(female to male) of passengers travelling with Invistico  Airline?

*
1 point

2.34

1.98

1.02

1.76

8) true and false, A and B , 0 and 1 are related to ?

*
1 point

Nominal Logistic Regression

Binary Logistic Regression

Multinomial Logistic Regression

Ordinal Logistic Regression

9) Compute the Male Loyal Customers Average Flight Distance?

*
1 point

2124.3

2542.1

8081.8

2679.0

In [ ]:
df.groupby(['Gender', 'Customer Type'])['Flight Distance'].mean().get('Male').get('Loyal Customer')

np.float64(2122.914077782218)

10) Logistic Regression _________ ?

*
1 point

Requires Less Training as compared to other Models

sensitive to overfitting and noise

All of the above

None of the above

11) ________metrics can not be applied for the model evaluation in case of logistic regression output to compare with dependent variable?

*
1 point

confusion Matrix

Accuracy

Mean-Squared-Error

None of the above

12)  Which of the following methods can be used to deal with null values:

*
1 point

dropping the null values

Replacing null values with the median

Imputing null values using mean imputation

All of the above

In [ ]:
df['Type of Travel'].unique()

array(['Personal Travel', 'Business travel', 'Business trav'],
      dtype=object)

In [ ]:
df['Satisfaction']

KeyError: 'Satisfaction'