## Source

Original Data source

https://github.com/CSSEGISandData/COVID-19

### Data Sources

1. Johns Hopkins University CSSE COVID-19 Dataset  
   Source: https://github.com/CSSEGISandData/COVID-19  
   License: CC BY 4.0

2. Pre-cleaned dataset provided by Intellipaat as `covid_19_clean_complete.csv`.  
   Original cleaning reference appears to be based on scripts from:  
   https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning  
   License: Not specified (no LICENSE file). Used only for educational purposes.

All datasets and code are used strictly for academic and non-commercial learning.

This dataset is a cleaned and combined derivative of the COVID-19 global data
maintained by the Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE).

Original Source (CC BY 4.0):
https://github.com/CSSEGISandData/COVID-19

A cleaned version of this dataset (`covid_19_clean_complete.csv`) was provided as part of an
educational assignment by Intellipaat. The dataset is further processed and transformed in
this project for analysis and visualization purposes.


Additional reference for the cleaning methodology:
https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning
(License not specified; referenced only for educational purposes.)

The original COVID-19 dataset by Johns Hopkins University CSSE is licensed under
Creative Commons Attribution 4.0 International (CC BY 4.0).

License Summary: https://creativecommons.org/licenses/by/4.0/
Full License Text: https://creativecommons.org/licenses/by/4.0/legalcode

**https://www.kaggle.com/datasets/imdevskp/corona-virus-report**

### Credits
Parts of the data cleaning logic in this project are adapted from the public
repository and Kaggle dataset :

GitHub: https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning  
Kaggle: https://www.kaggle.com/datasets/imdevskp/corona-virus-report  

Used strictly for educational purposes as part of the Intellipaat COVID-19
Capstone Project.

# Libraries

In [ ]:
!pip install wget

Requirement already satisfied: wget in /usr/local/lib/python3.12/dist-packages (3.2)

In [ ]:
# import libraries
# ================

# for date and time opeations
from datetime import datetime, timedelta
# for file and folder operations
import os
# for regular expression opeations
import re
# for listing files in a folder
import glob
# for getting web contents
import requests
# storing and analysing data
import pandas as pd
# for scraping web contents
from bs4 import BeautifulSoup
# to download data
import wget
# numerical analysis
import numpy as np

# Loading data

**Input covid_19_cleaned.csv is from Covid_19_data_cleaning.ipynb**

In [ ]:
full_table = pd.read_csv('/content/covid_19_cleaned.csv')

In [ ]:
full_table

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Albania,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,Algeria,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,Andorra,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,Angola,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,Sao Tome and Principe,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,Yemen,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,Comoros,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,Tajikistan,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,Lesotho,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [ ]:
full_table['Date'].nunique()

188

In [ ]:
full_table['Country/Region'].nunique()

187

In [ ]:
full_table.groupby('Country/Region')['Province/State'].nunique()

Country/Region
Afghanistan           1
Albania               1
Algeria               1
Andorra               1
Angola                1
                     ..
West Bank and Gaza    1
Western Sahara        1
Yemen                 1
Zambia                1
Zimbabwe              1
Name: Province/State, Length: 187, dtype: int64

In [ ]:
full_table.groupby('Country/Region')['Province/State'].nunique().sort_values(ascending=False)

Country/Region
China                 33
Canada                12
France                11
United Kingdom        11
Australia              8
                      ..
West Bank and Gaza     1
Western Sahara         1
Yemen                  1
Zambia                 1
Zimbabwe               1
Name: Province/State, Length: 187, dtype: int64

In [ ]:
full_table.groupby('Country/Region')['Province/State'].nunique().max()

33

In [ ]:
full_table.groupby('Country/Region')['Province/State'].nunique().sort_values(ascending=False)

Country/Region
China                 33
Canada                12
France                11
United Kingdom        11
Australia              8
                      ..
West Bank and Gaza     1
Western Sahara         1
Yemen                  1
Zambia                 1
Zimbabwe               1
Name: Province/State, Length: 187, dtype: int64

# Full Grouped

In [ ]:
# the below is to remove Province/State column by grouping up

In [ ]:
full_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  49068 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [ ]:
# Grouped by day, country
# =======================

full_grouped = full_table.groupby(['Date', 'Country/Region'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()

In [ ]:
full_grouped

             Date      Country/Region  Confirmed  Deaths  Recovered  Active
0      2020-01-22         Afghanistan          0       0          0       0
1      2020-01-22             Albania          0       0          0       0
2      2020-01-22             Algeria          0       0          0       0
3      2020-01-22             Andorra          0       0          0       0
4      2020-01-22              Angola          0       0          0       0
...           ...                 ...        ...     ...        ...     ...
35151  2020-07-27  West Bank and Gaza      10621      78       3752    6791
35152  2020-07-27      Western Sahara         10       1          8       1
35153  2020-07-27               Yemen       1691     483        833     375
35154  2020-07-27              Zambia       4552     140       2815    1597
35155  2020-07-27            Zimbabwe       2704      36        542    2126

[35156 rows x 6 columns]

In [ ]:
full_grouped.groupby(['Country/Region', 'Date', ])[['Confirmed', 'Deaths', 'Recovered']].sum()

                           Confirmed  Deaths  Recovered
Country/Region Date
Afghanistan    2020-01-22          0       0          0
               2020-01-23          0       0          0
               2020-01-24          0       0          0
               2020-01-25          0       0          0
               2020-01-26          0       0          0
...                              ...     ...        ...
Zimbabwe       2020-07-23       2124      28        510
               2020-07-24       2296      32        514
               2020-07-25       2434      34        518
               2020-07-26       2512      34        518
               2020-07-27       2704      36        542

[35156 rows x 3 columns]

In [ ]:
temp = full_grouped.groupby(['Country/Region', 'Date', ])[['Confirmed', 'Deaths', 'Recovered']]
temp = temp.sum().diff().reset_index() # diff calculates difference between this row and previous row

In [ ]:
temp

      Country/Region        Date  Confirmed  Deaths  Recovered
0        Afghanistan  2020-01-22        NaN     NaN        NaN
1        Afghanistan  2020-01-23        0.0     0.0        0.0
2        Afghanistan  2020-01-24        0.0     0.0        0.0
3        Afghanistan  2020-01-25        0.0     0.0        0.0
4        Afghanistan  2020-01-26        0.0     0.0        0.0
...              ...         ...        ...     ...        ...
35151       Zimbabwe  2020-07-23       90.0     2.0        0.0
35152       Zimbabwe  2020-07-24      172.0     4.0        4.0
35153       Zimbabwe  2020-07-25      138.0     2.0        4.0
35154       Zimbabwe  2020-07-26       78.0     0.0        0.0
35155       Zimbabwe  2020-07-27      192.0     2.0       24.0

[35156 rows x 5 columns]

In [ ]:
temp['Country/Region'].shift(1)

0               None
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
35151       Zimbabwe
35152       Zimbabwe
35153       Zimbabwe
35154       Zimbabwe
35155       Zimbabwe
Name: Country/Region, Length: 35156, dtype: object

In [ ]:
temp['Country/Region'] != temp['Country/Region'].shift(1)

# Move the entire Country/Region column down by 1 row, and fill the first row with NaN.
# Means it takes value of the previous row for that COLumn only
# that column's last row value cannot be seen in new dataframe

0         True
1        False
2        False
3        False
4        False
         ...
35151    False
35152    False
35153    False
35154    False
35155    False
Name: Country/Region, Length: 35156, dtype: bool

In [ ]:
mask = temp['Country/Region'] != temp['Country/Region'].shift(1)

# we are doing this
# because the 1st row of a country other than 1st country, assumes the previous day cases are last day of previous country
# which is wrong. the 1st row of any country has no previous day cases, so the New Cases would be Nan

temp.loc[mask, 'Confirmed'] = np.nan
temp.loc[mask, 'Deaths'] = np.nan
temp.loc[mask, 'Recovered'] = np.nan

# renaming columns
temp.columns = ['Country/Region', 'Date', 'New cases', 'New deaths', 'New recovered']
# =================================================================

# merging new values
full_grouped = pd.merge(full_grouped, temp, on=['Country/Region', 'Date'])

# filling na with 0
full_grouped = full_grouped.fillna(0)

# fixing data types
cols = ['New cases', 'New deaths', 'New recovered']
full_grouped[cols] = full_grouped[cols].astype('int')

In [ ]:
(full_grouped['New cases']<0).sum()  # these are possible if the cases are wrongly reported
# and then realised as these are not Covid cases and the new count is different

np.int64(33)

In [ ]:
full_grouped[(full_grouped['New cases']<0)]

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered
11667,2020-03-24,Guyana,5,1,0,4,-15,0,0
15325,2020-04-12,Uruguay,480,7,231,242,-21,0,7
16443,2020-04-18,Uganda,55,0,22,33,-1,0,2
17078,2020-04-22,France,155980,21342,40657,93981,-2188,544,1476
17548,2020-04-24,Spain,202990,22524,92355,88111,-10034,367,3105
17886,2020-04-26,New Zealand,1469,19,1180,270,-1,1,38
18240,2020-04-28,Lithuania,1344,44,536,764,-105,3,62
18387,2020-04-29,France,166543,24090,48228,94225,-2510,427,1342
18436,2020-04-29,Mauritius,332,10,306,16,-2,0,3
19022,2020-05-02,Portugal,25190,1023,1671,22496,-161,16,24
19073,2020-05-02,Zimbabwe,34,4,5,25,-6,0,0
19382,2020-05-04,New Zealand,1486,20,1302,164,-1,0,26
19873,2020-05-07,Ecuador,30298,1654,3433,25211,-1583,36,0
20060,2020-05-08,Ecuador,28818,1704,3433,23681,-1480,50,0
20526,2020-05-10,San Marino,628,41,126,461,-9,0,0
20621,2020-05-11,Ecuador,29509,2145,3433,23931,-50,18,0
20673,2020-05-11,Madagascar,186,0,101,85,-7,0,0
20833,2020-05-12,Honduras,2080,121,211,1748,-20,5,5
21005,2020-05-13,France,178184,27077,58786,92321,-165,83,888
21250,2020-05-14,Nepal,249,0,35,214,-1,0,0
22084,2020-05-19,Benin,130,2,83,45,-209,0,0
22614,2020-05-21,Uganda,160,0,66,94,-104,0,1
23345,2020-05-25,Spain,235400,26834,150376,58190,-372,-1918,0
23436,2020-05-26,France,182847,28533,65997,88317,-220,73,680
24745,2020-06-02,France,188582,28943,68930,90709,-766,107,372
24907,2020-06-03,China,84160,4638,77828,1694,-1,0,4
27948,2020-06-19,Italy,238011,34561,181907,21543,-148,47,1363
29607,2020-06-28,France,199476,29781,75774,93921,-719,0,1
30486,2020-07-03,Antigua and Barbuda,68,3,23,42,-1,0,0
32785,2020-07-15,Finland,7296,328,6880,88,-5,-1,80
32972,2020-07-16,Finland,7293,328,6880,85,-3,0,0
33935,2020-07-21,Jordan,1113,11,1034,68,-110,0,6
35092,2020-07-27,Niger,1132,69,1027,36,-4,0,0

In [ ]:
(full_grouped['New cases']==0).sum()

np.int64(15437)

In [ ]:
(full_grouped['New deaths']<0).sum()

np.int64(38)

In [ ]:
(full_grouped['New recovered']<0).sum()

np.int64(77)

In [ ]:
full_grouped['New cases'] = full_grouped['New cases'].apply(lambda x: 0 if x<0 else x)
full_grouped['New deaths'] = full_grouped['New deaths'].apply(lambda x: 0 if x<0 else x)
full_grouped['New recovered'] = full_grouped['New recovered'].apply(lambda x: 0 if x<0 else x)


full_grouped.head()

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0
1,2020-01-22,Albania,0,0,0,0,0,0,0
2,2020-01-22,Algeria,0,0,0,0,0,0,0
3,2020-01-22,Andorra,0,0,0,0,0,0,0
4,2020-01-22,Angola,0,0,0,0,0,0,0

In [ ]:
full_grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  object
 1   Country/Region  35156 non-null  object
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
dtypes: int64(7), object(2)
memory usage: 2.4+ MB

In [ ]:
full_table[['Country/Region', 'WHO Region']].drop_duplicates()

            Country/Region             WHO Region
0              Afghanistan  Eastern Mediterranean
1                  Albania                 Europe
2                  Algeria                 Africa
3                  Andorra                 Europe
4                   Angola                 Africa
..                     ...                    ...
256  Sao Tome and Principe                 Africa
257                  Yemen  Eastern Mediterranean
258                Comoros                 Africa
259             Tajikistan                 Europe
260                Lesotho                 Africa

[187 rows x 2 columns]

In [ ]:
full_table[['Country/Region', 'WHO Region']].drop_duplicates().set_index('Country/Region')['WHO Region']

Country/Region
Afghanistan              Eastern Mediterranean
Albania                                 Europe
Algeria                                 Africa
Andorra                                 Europe
Angola                                  Africa
                                 ...
Sao Tome and Principe                   Africa
Yemen                    Eastern Mediterranean
Comoros                                 Africa
Tajikistan                              Europe
Lesotho                                 Africa
Name: WHO Region, Length: 187, dtype: object

In [ ]:
who_region = (
    full_table[['Country/Region', 'WHO Region']]
    .drop_duplicates()
    .set_index('Country/Region')['WHO Region']
    .to_dict()
)

In [ ]:
# add 'WHO Region' column
full_grouped['WHO Region'] = full_grouped['Country/Region'].map(who_region)

# find missing values
full_grouped[full_grouped['WHO Region'].isna()]['Country/Region'].unique()

array([], dtype=object)

In [ ]:
# Check province ends with country
exceptions = {
    "Canada": "Manitoba",
    "China": "Gansu",
    "Australia": "South Australia"
}

def match_province(row):
    country = row['Country/Region']
    province = str(row['Province/State']).strip()

    # If country has an exception rule
    if country in exceptions:
        return province == exceptions[country]

    # Normal rule for all other countries
    return province.endswith(country)

mask = full_table.apply(match_province, axis=1)

matching_provinces = full_table[mask][['Province/State', 'Country/Region']].drop_duplicates()
matching_provinces

            Province/State         Country/Region
0              Afghanistan            Afghanistan
1                  Albania                Albania
2                  Algeria                Algeria
3                  Andorra                Andorra
4                   Angola                 Angola
..                     ...                    ...
256  Sao Tome and Principe  Sao Tome and Principe
257                  Yemen                  Yemen
258                Comoros                Comoros
259             Tajikistan             Tajikistan
260                Lesotho                Lesotho

[187 rows x 2 columns]

In [ ]:
lat_long = (
    full_table[mask][['Country/Region', 'Lat', 'Long']]
    .drop_duplicates()
)

In [ ]:
lat_long

            Country/Region        Lat       Long
0              Afghanistan  33.939110  67.709953
1                  Albania  41.153300  20.168300
2                  Algeria  28.033900   1.659600
3                  Andorra  42.506300   1.521800
4                   Angola -11.202700  17.873900
..                     ...        ...        ...
256  Sao Tome and Principe   0.186400   6.613100
257                  Yemen  15.552727  48.516388
258                Comoros -11.645500  43.333300
259             Tajikistan  38.861000  71.276100
260                Lesotho -29.610000  28.233600

[187 rows x 3 columns]

In [ ]:
full_grouped = full_grouped.merge(lat_long, on='Country/Region', how='left')

In [ ]:
full_grouped.shape

(35156, 12)

In [ ]:
full_grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  object
 1   Country/Region  35156 non-null  object
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  object
 10  Lat             35156 non-null  float64
 11  Long            35156 non-null  float64
dtypes: float64(2), int64(7), object(3)
memory usage: 3.2+ MB

In [ ]:
full_grouped.columns

Index(['Date', 'Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'WHO Region', 'Lat',
       'Long'],
      dtype='object')

In [ ]:
full_grouped_old_columns = full_grouped.columns.tolist()

In [ ]:
full_grouped_old_columns[:2] + full_grouped_old_columns[-2:] + full_grouped_old_columns[2:-2]

['Date',
 'Country/Region',
 'Lat',
 'Long',
 'Confirmed',
 'Deaths',
 'Recovered',
 'Active',
 'New cases',
 'New deaths',
 'New recovered',
 'WHO Region']

In [ ]:
len(full_grouped_old_columns[:2] + full_grouped_old_columns[-2:] + full_grouped_old_columns[2:-2]) == len(full_grouped.columns)

True

In [ ]:
full_grouped_new_column_order = full_grouped_old_columns[:2] + full_grouped_old_columns[-2:] + full_grouped_old_columns[2:-2]

In [ ]:
full_grouped = full_grouped[full_grouped_new_column_order]

In [ ]:
full_grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  datetime64[ns]
 1   Country/Region  35156 non-null  object
 2   Lat             35156 non-null  float64
 3   Long            35156 non-null  float64
 4   Confirmed       35156 non-null  int64
 5   Deaths          35156 non-null  int64
 6   Recovered       35156 non-null  int64
 7   Active          35156 non-null  int64
 8   New cases       35156 non-null  int64
 9   New deaths      35156 non-null  int64
 10  New recovered   35156 non-null  int64
 11  WHO Region      35156 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(7), object(2)
memory usage: 3.2+ MB

In [ ]:
# save as .csv file
full_grouped.to_csv('full_grouped.csv', index=False)

# Day wise

In [ ]:
full_grouped[full_grouped['Confirmed']!=0] \
                                    .groupby('Date')['Country/Region'] \
                                    .unique() \
                                    .apply(len)\
                                    .values

array([  6,   8,   9,  11,  13,  16,  16,  18,  20,  24,  25,  25,  25,
        26,  26,  26,  26,  26,  26,  26,  26,  26,  26,  27,  27,  27,
        27,  27,  28,  28,  30,  30,  31,  36,  41,  47,  51,  57,  61,
        66,  73,  76,  80,  84,  93,  94,  99, 102, 105, 111, 113, 120,
       133, 137, 143, 146, 150, 154, 161, 163, 168, 169, 171, 174, 175,
       176, 176, 176, 177, 179, 179, 180, 180, 180, 182, 183, 183, 183,
       183, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
       184, 184, 184, 184, 184, 184, 184, 184, 186, 186, 186, 186, 186,
       186, 186, 186, 186, 186, 186, 186, 186, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187])

In [ ]:
len(full_grouped[full_grouped['Confirmed']!=0] \
                                    .groupby('Date')['Country/Region'] \
                                    .unique() \
                                    .apply(len)\
                                    .values)

188

In [ ]:
# Day wise
# ========

# table
day_wise = full_grouped.groupby('Date')[['Confirmed', 'Deaths', 'Recovered',
                                        'Active', 'New cases', 'New deaths', 'New recovered']].sum().reset_index()

# number cases per 100 cases
day_wise['Deaths / 100 Cases'] = round((day_wise['Deaths']/day_wise['Confirmed'])*100, 2)
day_wise['Recovered / 100 Cases'] = round((day_wise['Recovered']/day_wise['Confirmed'])*100, 2)
day_wise['Deaths / 100 Recovered'] = round((day_wise['Deaths']/day_wise['Recovered'])*100, 2)

# no. of countries
day_wise['No. of countries'] = full_grouped[full_grouped['Confirmed']!=0] \
                                    .groupby('Date')['Country/Region'] \
                                    .unique() \
                                    .apply(len)\
                                    .values

# fillna by 0
cols = ['Deaths / 100 Cases', 'Recovered / 100 Cases', 'Deaths / 100 Recovered']
day_wise[cols] = day_wise[cols].fillna(0)

day_wise.head()

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,No. of countries
0,2020-01-22,555,17,28,510,0,0,0,3.06,5.05,60.71,6
1,2020-01-23,654,18,30,606,99,1,2,2.75,4.59,60.00,8
2,2020-01-24,941,26,36,879,287,8,6,2.76,3.83,72.22,9
3,2020-01-25,1434,42,39,1353,493,16,3,2.93,2.72,107.69,11
4,2020-01-26,2118,56,52,2010,684,14,13,2.64,2.46,107.69,13

In [ ]:
# save as .csv file
day_wise.to_csv('day_wise.csv', index=False)

# Country wise latest

In [ ]:
full_grouped

,Date,Country/Region,Lat,Long,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,2020-01-22,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,0,Eastern Mediterranean
1,2020-01-22,Albania,41.153300,20.168300,0,0,0,0,0,0,0,Europe
2,2020-01-22,Algeria,28.033900,1.659600,0,0,0,0,0,0,0,Africa
3,2020-01-22,Andorra,42.506300,1.521800,0,0,0,0,0,0,0,Europe
4,2020-01-22,Angola,-11.202700,17.873900,0,0,0,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
35151,2020-07-27,West Bank and Gaza,31.952200,35.233200,10621,78,3752,6791,152,2,0,Eastern Mediterranean
35152,2020-07-27,Western Sahara,24.215500,-12.885800,10,1,8,1,0,0,0,Africa
35153,2020-07-27,Yemen,15.552727,48.516388,1691,483,833,375,10,4,36,Eastern Mediterranean
35154,2020-07-27,Zambia,-13.133897,27.849332,4552,140,2815,1597,71,1,465,Africa
35155,2020-07-27,Zimbabwe,-19.015438,29.154857,2704,36,542,2126,192,2,24,Africa

In [ ]:
# Country wise
# ============

full_grouped['Date'] = pd.to_datetime(full_grouped['Date'])

# getting latest values, we get 1 row per country
country_wise = full_grouped[full_grouped['Date']==max(full_grouped['Date'])] \
                    .reset_index(drop=True) \
                    .drop('Date', axis=1)  # date is same for all selected rows

print(country_wise.shape)


# per 100 cases
country_wise['Deaths / 100 Cases'] = round((country_wise['Deaths']/country_wise['Confirmed'])*100, 2)
country_wise['Recovered / 100 Cases'] = round((country_wise['Recovered']/country_wise['Confirmed'])*100, 2)
country_wise['Deaths / 100 Recovered'] = round((country_wise['Deaths']/country_wise['Recovered'])*100, 2)

cols = ['Deaths / 100 Cases', 'Recovered / 100 Cases', 'Deaths / 100 Recovered']
country_wise[cols] = country_wise[cols].fillna(0)


# 1 week increase and % change
# ============================

today = full_grouped[full_grouped['Date']==max(full_grouped['Date'])] \
            .reset_index(drop=True) \
            .drop('Date', axis=1)[['Country/Region', 'Confirmed']]

last_week = full_grouped[full_grouped['Date']==max(full_grouped['Date'])-timedelta(days=7)] \
                .reset_index(drop=True) \
                .drop('Date', axis=1)[['Country/Region', 'Confirmed']]

temp = pd.merge(today, last_week, on='Country/Region', suffixes=(' today', ' last week')) # suffix since column from both df to be merged has same name
temp['1 week change'] = temp['Confirmed today'] - temp['Confirmed last week']
temp = temp[['Country/Region', 'Confirmed last week', '1 week change']]

country_wise = pd.merge(country_wise, temp, on='Country/Region')
country_wise['1 week % increase'] = round(country_wise['1 week change']/country_wise['Confirmed last week']*100, 2)

# to bring WHO to last, pop() removes the column and returns it, and assigning it back places it at the end.
country_wise['WHO Region'] = country_wise.pop('WHO Region')
country_wise.head()

(187, 11)

,Country/Region,Lat,Long,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,33.93911,67.709953,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,41.15330,20.168300,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,28.03390,1.659600,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,42.50630,1.521800,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,-11.20270,17.873900,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [ ]:
country_wise.shape

(187, 17)

In [ ]:
country_wise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Lat                     187 non-null    float64
 2   Long                    187 non-null    float64
 3   Confirmed               187 non-null    int64
 4   Deaths                  187 non-null    int64
 5   Recovered               187 non-null    int64
 6   Active                  187 non-null    int64
 7   New cases               187 non-null    int64
 8   New deaths              187 non-null    int64
 9   New recovered           187 non-null    int64
 10  Deaths / 100 Cases      187 non-null    float64
 11  Recovered / 100 Cases   187 non-null    float64
 12  Deaths / 100 Recovered  187 non-null    float64
 13  Confirmed last week     187 non-null    int64
 14  1 week change           187 non-null    int64
 15  1 week % increase       187 non-null    float64
 16  WHO Region              187 non-null    object
dtypes: float64(6), int64(9), object(2)
memory usage: 25.0+ KB

In [ ]:
# save as .csv file
country_wise.to_csv('country_wise_latest.csv', index=False)