# Project : Analyzing the trends of COVID-19 with Python

## Problem Statement:
Given data about COVID-19 patients, write code to visualize the impact and analyze the trend of rate of infection and recovery as well as make predictions about the number of cases expected a week in future based on the current trends.

## Dataset:
CSV and Excel files containing data about the number of COVID-19 confirmed deaths and recovered patients both around the world and in India. Download Link

## Guidelines:
 - ● Usepandas to accumulate data from multiple data files.
 - ● Useplotly (visualization library) to create interactive visualizations.
 - ● UseFacebook prophet library to make time series models.
 - ● Visualize the prediction by combining these technologies.

## Source

Original Data source

https://github.com/CSSEGISandData/COVID-19

### Data Sources

1. Johns Hopkins University CSSE COVID-19 Dataset  
   Source: https://github.com/CSSEGISandData/COVID-19  
   License: CC BY 4.0

2. Pre-cleaned dataset provided by Intellipaat as `covid_19_clean_complete.csv`.  
   Original cleaning reference appears to be based on scripts from:  
   https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning  
   License: Not specified (no LICENSE file). Used only for educational purposes.

All datasets and code are used strictly for academic and non-commercial learning.

Source code for this file : http://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning

This dataset is a cleaned and combined derivative of the COVID-19 global data
maintained by the Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE).

Original Source (CC BY 4.0):
https://github.com/CSSEGISandData/COVID-19

A cleaned version of this dataset (`covid_19_clean_complete.csv`) was provided as part of an
educational assignment by Intellipaat. The dataset is further processed and transformed in
this project for analysis and visualization purposes.


Additional reference for the cleaning methodology:
https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning
(License not specified; referenced only for educational purposes.)

The original COVID-19 dataset by Johns Hopkins University CSSE is licensed under
Creative Commons Attribution 4.0 International (CC BY 4.0).

License Summary: https://creativecommons.org/licenses/by/4.0/
Full License Text: https://creativecommons.org/licenses/by/4.0/legalcode

**https://www.kaggle.com/datasets/imdevskp/corona-virus-report**

## Analysis and Cleaning

**Input Data covid_19_clean_complete.csv is provided in assignment**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import plotly.express as px

In [ ]:
# only one csv is here in this project, so df can be used
df = pd.read_csv('/content/covid_19_clean_complete.csv')

In [ ]:
df

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [ ]:
df.groupby('Country/Region')

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum())

/tmp/ipython-input-1293772041.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum())

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
Country/Region,,,,,,,,,,
Afghanistan,188,0,0,0,0,0,0,0,0,0
Albania,188,0,0,0,0,0,0,0,0,0
Algeria,188,0,0,0,0,0,0,0,0,0
Andorra,188,0,0,0,0,0,0,0,0,0
Angola,188,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,188,0,0,0,0,0,0,0,0,0
Western Sahara,188,0,0,0,0,0,0,0,0,0
Yemen,188,0,0,0,0,0,0,0,0,0
Zambia,188,0,0,0,0,0,0,0,0,0
Zimbabwe,188,0,0,0,0,0,0,0,0,0

In [ ]:
# df.groupby('Country/Region').isnull().sum()

# AttributeError: 'DataFrameGroupBy' object has no attribute 'isnull'

In [ ]:
df.isnull().groupby(df['Country/Region']).sum()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
Country/Region,,,,,,,,,,
Afghanistan,188,0,0,0,0,0,0,0,0,0
Albania,188,0,0,0,0,0,0,0,0,0
Algeria,188,0,0,0,0,0,0,0,0,0
Andorra,188,0,0,0,0,0,0,0,0,0
Angola,188,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,188,0,0,0,0,0,0,0,0,0
Western Sahara,188,0,0,0,0,0,0,0,0,0
Yemen,188,0,0,0,0,0,0,0,0,0
Zambia,188,0,0,0,0,0,0,0,0,0
Zimbabwe,188,0,0,0,0,0,0,0,0,0

In [ ]:
# checking if above 2 methods return same result

In [ ]:
(df.groupby('Country/Region').apply(lambda g: g.isnull().sum()) == df.isnull().groupby(df['Country/Region']).sum()).sum().sum()

/tmp/ipython-input-2611636549.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  (df.groupby('Country/Region').apply(lambda g: g.isnull().sum()) == df.isnull().groupby(df['Country/Region']).sum()).sum().sum()

np.int64(1870)

In [ ]:
(df.groupby('Country/Region').apply(lambda g: g.isnull().sum())).compare(df.isnull().groupby(df['Country/Region']).sum())

/tmp/ipython-input-3928524455.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  (df.groupby('Country/Region').apply(lambda g: g.isnull().sum())).compare(df.isnull().groupby(df['Country/Region']).sum())

Empty DataFrame
Columns: []
Index: []

In [ ]:
(df.groupby('Country/Region').apply(lambda g: g.isnull().sum())).equals(df.isnull().groupby(df['Country/Region']).sum())

/tmp/ipython-input-537289415.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  (df.groupby('Country/Region').apply(lambda g: g.isnull().sum())).equals(df.isnull().groupby(df['Country/Region']).sum())

True

In [ ]:
null_counts_per_country = df.groupby('Country/Region').apply(lambda g: g.isnull().sum())

# Now find columns that have any non-zero missing values in any group
cols_with_missing = null_counts_per_country.columns[(null_counts_per_country > 0).any()]
print(cols_with_missing)

Index(['Province/State'], dtype='object')

/tmp/ipython-input-4068198011.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  null_counts_per_country = df.groupby('Country/Region').apply(lambda g: g.isnull().sum())

In [ ]:
df.isnull().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  49068 non-null  bool
 1   Country/Region  49068 non-null  bool
 2   Lat             49068 non-null  bool
 3   Long            49068 non-null  bool
 4   Date            49068 non-null  bool
 5   Confirmed       49068 non-null  bool
 6   Deaths          49068 non-null  bool
 7   Recovered       49068 non-null  bool
 8   Active          49068 non-null  bool
 9   WHO Region      49068 non-null  bool
dtypes: bool(10)
memory usage: 479.3 KB

In [ ]:
cols_with_missing

Index(['Province/State'], dtype='object')

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing]

/tmp/ipython-input-1583013668.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing]

                    Province/State
Country/Region
Afghanistan                    188
Albania                        188
Algeria                        188
Andorra                        188
Angola                         188
...                            ...
West Bank and Gaza             188
Western Sahara                 188
Yemen                          188
Zambia                         188
Zimbabwe                       188

[187 rows x 1 columns]

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing].max()

/tmp/ipython-input-777899252.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing].max()

Province/State    188
dtype: int64

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing].value_counts()

/tmp/ipython-input-3524176765.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum())[cols_with_missing].value_counts()

Province/State
188               183
0                   4
Name: count, dtype: int64

In [ ]:
len(df['Country/Region'].unique())

187

In [ ]:
# 4 countries have NO NULL values in Province/State

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum()).loc['United Kingdom', cols_with_missing]

/tmp/ipython-input-4083687295.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum()).loc['United Kingdom', cols_with_missing]

Province/State    188
Name: United Kingdom, dtype: int64

In [ ]:
# percentage of missing in the UK
df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc['United Kingdom', cols_with_missing]

/tmp/ipython-input-1361797866.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc['United Kingdom', cols_with_missing]

Province/State    9.090909
Name: United Kingdom, dtype: float64

In [ ]:
df[df['Country/Region']=='United Kingdom'].isnull().sum()

Province/State    188
Country/Region      0
Lat                 0
Long                0
Date                0
Confirmed           0
Deaths              0
Recovered           0
Active              0
WHO Region          0
dtype: int64

In [ ]:
len(df[df['Country/Region']=='United Kingdom'])

2068

In [ ]:
188/2068

0.09090909090909091

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc["India", cols_with_missing]

/tmp/ipython-input-3555929643.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc["India", cols_with_missing]

Province/State    100.0
Name: India, dtype: float64

In [ ]:
len(df[df['Country/Region']=='India'])

188

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing] # loc of all rows

/tmp/ipython-input-3510648787.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing] # loc of all rows

                    Province/State
Country/Region
Afghanistan                  100.0
Albania                      100.0
Algeria                      100.0
Andorra                      100.0
Angola                       100.0
...                            ...
West Bank and Gaza           100.0
Western Sahara               100.0
Yemen                        100.0
Zambia                       100.0
Zimbabwe                     100.0

[187 rows x 1 columns]

In [ ]:
df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing].value_counts()

/tmp/ipython-input-1022562637.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing].value_counts()

Province/State
100.000000        179
0.000000            4
9.090909            2
25.000000           1
50.000000           1
Name: count, dtype: int64

In [ ]:
counts_per_country = df['Country/Region'].value_counts()
print(counts_per_country.sort_values())

Country/Region
Algeria            188
Barbados           188
Bangladesh         188
Bahrain            188
Bahamas            188
                  ...
Australia         1504
France            2068
United Kingdom    2068
Canada            2256
China             6204
Name: count, Length: 187, dtype: int64

In [ ]:
df[(df['Country/Region']=='United Kingdom') & (df['Confirmed']>0) & (df['Province/State'].isnull())]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
2570,NaN,United Kingdom,55.3781,-3.436,2020-01-31,2,0,0,2,Europe
2831,NaN,United Kingdom,55.3781,-3.436,2020-02-01,2,0,0,2,Europe
3092,NaN,United Kingdom,55.3781,-3.436,2020-02-02,2,0,0,2,Europe
3353,NaN,United Kingdom,55.3781,-3.436,2020-02-03,8,0,0,8,Europe
3614,NaN,United Kingdom,55.3781,-3.436,2020-02-04,8,0,0,8,Europe
...,...,...,...,...,...,...,...,...,...,...
47984,NaN,United Kingdom,55.3781,-3.436,2020-07-23,297146,45554,0,251592,Europe
48245,NaN,United Kingdom,55.3781,-3.436,2020-07-24,297914,45677,0,252237,Europe
48506,NaN,United Kingdom,55.3781,-3.436,2020-07-25,298681,45738,0,252943,Europe
48767,NaN,United Kingdom,55.3781,-3.436,2020-07-26,299426,45752,0,253674,Europe
49028,NaN,United Kingdom,55.3781,-3.436,2020-07-27,300111,45759,0,254352,Europe

In [ ]:
df[(df['Country/Region']=='United Kingdom') & (df['Confirmed']>0) & (df['Province/State'].notnull())]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
11180,Gibraltar,United Kingdom,36.140800,-5.353600,2020-03-04,1,0,0,1,Europe
11441,Gibraltar,United Kingdom,36.140800,-5.353600,2020-03-05,1,0,0,1,Europe
11702,Gibraltar,United Kingdom,36.140800,-5.353600,2020-03-06,1,0,0,1,Europe
11963,Gibraltar,United Kingdom,36.140800,-5.353600,2020-03-07,1,0,0,1,Europe
12224,Gibraltar,United Kingdom,36.140800,-5.353600,2020-03-08,1,0,0,1,Europe
...,...,...,...,...,...,...,...,...,...,...
49027,Montserrat,United Kingdom,16.742498,-62.187366,2020-07-27,12,1,10,1,Europe
49052,Anguilla,United Kingdom,18.220600,-63.068600,2020-07-27,3,0,3,0,Europe
49053,British Virgin Islands,United Kingdom,18.420700,-64.640000,2020-07-27,8,1,7,0,Europe
49054,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,2020-07-27,99,2,36,61,Europe
49059,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,2020-07-27,13,0,13,0,Europe

In [ ]:
# Filter UK data
uk_df = df[df['Country/Region'] == 'United Kingdom']

# Sum of confirmed cases where Province/State is null (country-level aggregate)
null_province_uk = uk_df[uk_df['Province/State'].isnull()].groupby('Date')['Confirmed'].sum()

# Sum of confirmed cases for all provinces (province-level detail)
province_cases_uk = uk_df[uk_df['Province/State'].notnull()].groupby('Date')['Confirmed'].sum()

# Merge the two series for comparison
comparison_uk = pd.DataFrame({
    'Null_Province_Confirmed': null_province_uk,
    'Province_Confirmed_Sum': province_cases_uk
}).fillna(0)

# Inspect discrepancies or equality for multiple dates
print(comparison_uk.head(20))

# Check if null province cases equal to sum of provinces cases (aggregation)
comparison_uk['Is_Aggregate'] = comparison_uk['Null_Province_Confirmed'] >= comparison_uk['Province_Confirmed_Sum']

print(comparison_uk[['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']])

            Null_Province_Confirmed  Province_Confirmed_Sum
Date
2020-01-22                        0                       0
2020-01-23                        0                       0
2020-01-24                        0                       0
2020-01-25                        0                       0
2020-01-26                        0                       0
2020-01-27                        0                       0
2020-01-28                        0                       0
2020-01-29                        0                       0
2020-01-30                        0                       0
2020-01-31                        2                       0
2020-02-01                        2                       0
2020-02-02                        2                       0
2020-02-03                        8                       0
2020-02-04                        8                       0
2020-02-05                        9                       0
2020-02-06                        9                       0
2020-02-07                        9                       0
2020-02-08                       13                       0
2020-02-09                       14                       0
2020-02-10                       14                       0
            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-01-22                        0                       0          True
2020-01-23                        0                       0          True
2020-01-24                        0                       0          True
2020-01-25                        0                       0          True
2020-01-26                        0                       0          True
...                             ...                     ...           ...
2020-07-23                   297146                    1585          True
2020-07-24                   297914                    1586          True
2020-07-25                   298681                    1589          True
2020-07-26                   299426                    1594          True
2020-07-27                   300111                    1597          True

[188 rows x 3 columns]

In [ ]:
(comparison_uk['Is_Aggregate'] == False)

Date
2020-01-22    False
2020-01-23    False
2020-01-24    False
2020-01-25    False
2020-01-26    False
              ...
2020-07-23    False
2020-07-24    False
2020-07-25    False
2020-07-26    False
2020-07-27    False
Name: Is_Aggregate, Length: 188, dtype: bool

In [ ]:
(comparison_uk['Is_Aggregate'] == False).any()

np.False_

In [ ]:
# Filter Denmark data
denmark_df = df[df['Country/Region'] == 'Denmark']

# Sum of confirmed cases where Province/State is null (country-level aggregate)
null_province_denmark = denmark_df[denmark_df['Province/State'].isnull()].groupby('Date')['Confirmed'].sum()

# Sum of confirmed cases for all provinces (province-level detail)
province_cases_denmark = denmark_df[denmark_df['Province/State'].notnull()].groupby('Date')['Confirmed'].sum()

# Merge the two series for comparison
comparison_denmark = pd.DataFrame({
    'Null_Province_Confirmed': null_province_denmark,
    'Province_Confirmed_Sum': province_cases_denmark
}).fillna(0)

# Inspect discrepancies or equality for multiple dates
print(comparison_denmark.head(20))

# Check if null province cases equal to sum of provinces cases (aggregation)
comparison_denmark['Is_Aggregate'] = comparison_denmark['Null_Province_Confirmed'] >= comparison_denmark['Province_Confirmed_Sum']

print(comparison_denmark[['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']])

            Null_Province_Confirmed  Province_Confirmed_Sum
Date
2020-01-22                        0                       0
2020-01-23                        0                       0
2020-01-24                        0                       0
2020-01-25                        0                       0
2020-01-26                        0                       0
2020-01-27                        0                       0
2020-01-28                        0                       0
2020-01-29                        0                       0
2020-01-30                        0                       0
2020-01-31                        0                       0
2020-02-01                        0                       0
2020-02-02                        0                       0
2020-02-03                        0                       0
2020-02-04                        0                       0
2020-02-05                        0                       0
2020-02-06                        0                       0
2020-02-07                        0                       0
2020-02-08                        0                       0
2020-02-09                        0                       0
2020-02-10                        0                       0
            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-01-22                        0                       0          True
2020-01-23                        0                       0          True
2020-01-24                        0                       0          True
2020-01-25                        0                       0          True
2020-01-26                        0                       0          True
...                             ...                     ...           ...
2020-07-23                    13390                     191          True
2020-07-24                    13438                     191          True
2020-07-25                    13438                     192          True
2020-07-26                    13438                     214          True
2020-07-27                    13547                     214          True

[188 rows x 3 columns]

In [ ]:
(comparison_denmark['Is_Aggregate'] == False).any()

np.False_

In [ ]:
# Compute % of nulls per country for the selected columns
null_pct = df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing]

# Filter rows where null % > 0 and < 100
partial_nulls = null_pct[(null_pct > 0) & (null_pct < 100)].dropna(how='all')  # drop rows where all columns are NaN
print(partial_nulls)

                Province/State
Country/Region
Denmark              50.000000
France                9.090909
Netherlands          25.000000
United Kingdom        9.090909

/tmp/ipython-input-1841418090.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  null_pct = df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing]

In [ ]:
# Filter France data
france_df = df[df['Country/Region'] == 'France']

# Sum of confirmed cases where Province/State is null (country-level aggregate)
null_province_france = france_df[france_df['Province/State'].isnull()].groupby('Date')['Confirmed'].sum()

# Sum of confirmed cases for all provinces (province-level detail)
province_cases_france = france_df[france_df['Province/State'].notnull()].groupby('Date')['Confirmed'].sum()

# Merge the two series for comparison
comparison_france = pd.DataFrame({
    'Null_Province_Confirmed': null_province_france,
    'Province_Confirmed_Sum': province_cases_france
}).fillna(0)

# Inspect discrepancies or equality for multiple dates
print(comparison_france.head(20))

# Check if null province cases equal to sum of provinces cases (aggregation)
comparison_france['Is_Aggregate'] = comparison_france['Null_Province_Confirmed'] >= comparison_france['Province_Confirmed_Sum']

print(comparison_france[['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']])

            Null_Province_Confirmed  Province_Confirmed_Sum
Date
2020-01-22                        0                       0
2020-01-23                        0                       0
2020-01-24                        2                       0
2020-01-25                        3                       0
2020-01-26                        3                       0
2020-01-27                        3                       0
2020-01-28                        4                       0
2020-01-29                        5                       0
2020-01-30                        5                       0
2020-01-31                        5                       0
2020-02-01                        6                       0
2020-02-02                        6                       0
2020-02-03                        6                       0
2020-02-04                        6                       0
2020-02-05                        6                       0
2020-02-06                        6                       0
2020-02-07                        6                       0
2020-02-08                       11                       0
2020-02-09                       11                       0
2020-02-10                       11                       0
            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-01-22                        0                       0          True
2020-01-23                        0                       0          True
2020-01-24                        2                       0          True
2020-01-25                        3                       0          True
2020-01-26                        3                       0          True
...                             ...                     ...           ...
2020-07-23                   205476                   11191          True
2020-07-24                   206418                   11379          True
2020-07-25                   206334                   11467          True
2020-07-26                   206334                   11467          True
2020-07-27                   208665                   11687          True

[188 rows x 3 columns]

In [ ]:
(comparison_france['Is_Aggregate'] == False).any()

np.False_

In [ ]:
# Filter Netherlands data
netherlands_df = df[df['Country/Region'] == 'Netherlands']

# Sum of confirmed cases where Province/State is null (country-level aggregate)
null_province_netherlands = netherlands_df[netherlands_df['Province/State'].isnull()].groupby('Date')['Confirmed'].sum()

# Sum of confirmed cases for all provinces (province-level detail)
province_cases_netherlands = netherlands_df[netherlands_df['Province/State'].notnull()].groupby('Date')['Confirmed'].sum()

# Merge the two series for comparison
comparison_netherlands = pd.DataFrame({
    'Null_Province_Confirmed': null_province_netherlands,
    'Province_Confirmed_Sum': province_cases_netherlands
}).fillna(0)

# Inspect discrepancies or equality for multiple dates
print(comparison_netherlands.head(20))

# Check if null province cases equal to sum of provinces cases (aggregation)
comparison_netherlands['Is_Aggregate'] = comparison_netherlands['Null_Province_Confirmed'] >= comparison_netherlands['Province_Confirmed_Sum']

print(comparison_netherlands[['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']])

            Null_Province_Confirmed  Province_Confirmed_Sum
Date
2020-01-22                        0                       0
2020-01-23                        0                       0
2020-01-24                        0                       0
2020-01-25                        0                       0
2020-01-26                        0                       0
2020-01-27                        0                       0
2020-01-28                        0                       0
2020-01-29                        0                       0
2020-01-30                        0                       0
2020-01-31                        0                       0
2020-02-01                        0                       0
2020-02-02                        0                       0
2020-02-03                        0                       0
2020-02-04                        0                       0
2020-02-05                        0                       0
2020-02-06                        0                       0
2020-02-07                        0                       0
2020-02-08                        0                       0
2020-02-09                        0                       0
2020-02-10                        0                       0
            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-01-22                        0                       0          True
2020-01-23                        0                       0          True
2020-01-24                        0                       0          True
2020-01-25                        0                       0          True
2020-01-26                        0                       0          True
...                             ...                     ...           ...
2020-07-23                    52404                     226          True
2020-07-24                    52595                     231          True
2020-07-25                    52732                     241          True
2020-07-26                    52732                     262          True
2020-07-27                    53151                     262          True

[188 rows x 3 columns]

In [ ]:
print(comparison_netherlands[comparison_netherlands['Null_Province_Confirmed']>0][['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']])

            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-02-27                        1                       0          True
2020-02-28                        1                       0          True
2020-02-29                        6                       0          True
2020-03-01                       10                       0          True
2020-03-02                       18                       0          True
...                             ...                     ...           ...
2020-07-23                    52404                     226          True
2020-07-24                    52595                     231          True
2020-07-25                    52732                     241          True
2020-07-26                    52732                     262          True
2020-07-27                    53151                     262          True

[152 rows x 3 columns]

In [ ]:
(comparison_uk[comparison_uk['Null_Province_Confirmed']>0][['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']]).head(30)

            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-01-31                        2                       0          True
2020-02-01                        2                       0          True
2020-02-02                        2                       0          True
2020-02-03                        8                       0          True
2020-02-04                        8                       0          True
2020-02-05                        9                       0          True
2020-02-06                        9                       0          True
2020-02-07                        9                       0          True
2020-02-08                       13                       0          True
2020-02-09                       14                       0          True
2020-02-10                       14                       0          True
2020-02-11                       15                       0          True
2020-02-12                       16                       0          True
2020-02-13                       17                       0          True
2020-02-14                       18                       0          True
2020-02-15                       18                       0          True
2020-02-16                       18                       0          True
2020-02-17                       19                       0          True
2020-02-18                       19                       0          True
2020-02-19                       20                       0          True
2020-02-20                       22                       0          True
2020-02-21                       23                       0          True
2020-02-22                       23                       0          True
2020-02-23                       28                       0          True
2020-02-24                       30                       0          True
2020-02-25                       34                       0          True
2020-02-26                       37                       0          True
2020-02-27                       44                       0          True
2020-02-28                       56                       0          True
2020-02-29                       61                       0          True

In [ ]:
(comparison_denmark[comparison_denmark['Null_Province_Confirmed']>0][['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']]).head(30)

            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-02-27                        1                       0          True
2020-02-28                        1                       0          True
2020-02-29                        3                       0          True
2020-03-01                        4                       0          True
2020-03-02                        4                       0          True
2020-03-03                        6                       0          True
2020-03-04                       10                       1          True
2020-03-05                       10                       1          True
2020-03-06                       23                       1          True
2020-03-07                       23                       1          True
2020-03-08                       35                       2          True
2020-03-09                       90                       2          True
2020-03-10                      262                       2          True
2020-03-11                      442                       2          True
2020-03-12                      615                       2          True
2020-03-13                      801                       3          True
2020-03-14                      827                       9          True
2020-03-15                      864                      11          True
2020-03-16                      914                      18          True
2020-03-17                      977                      47          True
2020-03-18                     1057                      58          True
2020-03-19                     1151                      72          True
2020-03-20                     1255                      80          True
2020-03-21                     1326                      92          True
2020-03-22                     1395                     115          True
2020-03-23                     1450                     118          True
2020-03-24                     1591                     122          True
2020-03-25                     1724                     132          True
2020-03-26                     1877                     140          True
2020-03-27                     2046                     144          True

In [ ]:
(comparison_netherlands[comparison_netherlands['Null_Province_Confirmed']>0][['Null_Province_Confirmed', 'Province_Confirmed_Sum', 'Is_Aggregate']]).head(30)

            Null_Province_Confirmed  Province_Confirmed_Sum  Is_Aggregate
Date
2020-02-27                        1                       0          True
2020-02-28                        1                       0          True
2020-02-29                        6                       0          True
2020-03-01                       10                       0          True
2020-03-02                       18                       0          True
2020-03-03                       24                       0          True
2020-03-04                       38                       0          True
2020-03-05                       82                       0          True
2020-03-06                      128                       0          True
2020-03-07                      188                       0          True
2020-03-08                      265                       0          True
2020-03-09                      321                       0          True
2020-03-10                      382                       0          True
2020-03-11                      503                       0          True
2020-03-12                      503                       0          True
2020-03-13                      804                       2          True
2020-03-14                      959                       3          True
2020-03-15                     1135                       3          True
2020-03-16                     1413                       3          True
2020-03-17                     1705                       6          True
2020-03-18                     2051                       7          True
2020-03-19                     2460                       7          True
2020-03-20                     2994                       9          True
2020-03-21                     3631                       9          True
2020-03-22                     4204                      13          True
2020-03-23                     4749                      15          True
2020-03-24                     5560                      20          True
2020-03-25                     6412                      26          True
2020-03-26                     7431                      37          True
2020-03-27                     8603                      44          True

In [ ]:
df.groupby('Country/Region')['Confirmed'].sum()

Country/Region
Afghanistan           1936390
Albania                196702
Algeria               1179755
Andorra                 94404
Angola                  22662
                       ...
West Bank and Gaza     233461
Western Sahara            901
Yemen                   67180
Zambia                 129421
Zimbabwe                50794
Name: Confirmed, Length: 187, dtype: int64

In [ ]:
df.groupby('Country/Region')['Confirmed'].sum()['India']

np.int64(40883464)

In [ ]:
denmark_df['Province/State'].unique()

array(['Faroe Islands', nan], dtype=object)

In [ ]:
netherlands_df['Province/State'].unique()

array(['Aruba', 'Curacao', 'Sint Maarten', nan], dtype=object)

In [ ]:
france_df['Province/State'].unique()

array(['French Guiana', 'French Polynesia', 'Guadeloupe', 'Mayotte',
       'New Caledonia', 'Reunion', 'Saint Barthelemy', 'St Martin',
       'Martinique', nan, 'Saint Pierre and Miquelon'], dtype=object)

In [ ]:
netherlands_df['Province/State'].unique()

array(['Aruba', 'Curacao', 'Sint Maarten', nan], dtype=object)

In [ ]:
uk_df['Province/State'].unique()

array(['Bermuda', 'Cayman Islands', 'Channel Islands', 'Gibraltar',
       'Isle of Man', 'Montserrat', nan, 'Anguilla',
       'British Virgin Islands', 'Turks and Caicos Islands',
       'Falkland Islands (Malvinas)'], dtype=object)

In [ ]:
len(netherlands_df['Province/State'].unique())

4

In [ ]:
len(france_df['Province/State'].unique())

11

In [ ]:
len(uk_df['Province/State'].unique())

11

In [ ]:
df.groupby('Province/State')['Country/Region'].nunique().max()

1

In [ ]:
# so each province belong to one country only

In [ ]:
# Compute % of nulls per country for the selected columns
null_pct = df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing]

full_nulls = null_pct[(null_pct == 100)].dropna(how='all')  # drop rows where all columns are NaN
print(full_nulls)

                    Province/State
Country/Region
Afghanistan                  100.0
Albania                      100.0
Algeria                      100.0
Andorra                      100.0
Angola                       100.0
...                            ...
West Bank and Gaza           100.0
Western Sahara               100.0
Yemen                        100.0
Zambia                       100.0
Zimbabwe                     100.0

[179 rows x 1 columns]

/tmp/ipython-input-1188067836.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  null_pct = df.groupby('Country/Region').apply(lambda g: g.isnull().sum()/len(g)*100).loc[:, cols_with_missing]

In [ ]:
no_nulls = null_pct[(null_pct == 0)].dropna(how='all')  # drop rows where all columns are NaN
print(no_nulls)

                Province/State
Country/Region
Australia                  0.0
Canada                     0.0
China                      0.0
Greenland                  0.0

In [ ]:
def fill_null_provinces(df):
    """
    Fills null values in 'Province/State' column based on country-specific logic:
    - If all provinces for a country are null → fill with country name
    - If some provinces are null and others are not → fill with 'Mainland <CountryName>'
    - If province equals country name → leave as-is
    """
    df1 = df.copy()

    # Group by country
    for country in df1['Country/Region'].unique():
        country_mask = df1['Country/Region'] == country
        province_values = df1.loc[country_mask, 'Province/State']

        # Case 1: All provinces null
        if province_values.isnull().all():
            df1.loc[country_mask, 'Province/State'] = country

        # Case 2: Some provinces null, some not
        elif province_values.isnull().any():
            df1.loc[(country_mask) & (df['Province/State'].isnull()), 'Province/State'] = f'Mainland {country}'

        # Case 3: Province equals country name → leave as-is (already handled implicitly)

    return df1

In [ ]:
df_cleaned = fill_null_provinces(df)

In [ ]:
df_cleaned.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [ ]:
df_cleaned[df_cleaned['Country/Region']=='United Kingdom']

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
215,Bermuda,United Kingdom,32.3078,-64.7505,2020-01-22,0,0,0,0,Europe
216,Cayman Islands,United Kingdom,19.3133,-81.2546,2020-01-22,0,0,0,0,Europe
217,Channel Islands,United Kingdom,49.3723,-2.3644,2020-01-22,0,0,0,0,Europe
218,Gibraltar,United Kingdom,36.1408,-5.3536,2020-01-22,0,0,0,0,Europe
219,Isle of Man,United Kingdom,54.2361,-4.5481,2020-01-22,0,0,0,0,Europe
...,...,...,...,...,...,...,...,...,...,...
49028,Mainland United Kingdom,United Kingdom,55.3781,-3.4360,2020-07-27,300111,45759,0,254352,Europe
49052,Anguilla,United Kingdom,18.2206,-63.0686,2020-07-27,3,0,3,0,Europe
49053,British Virgin Islands,United Kingdom,18.4207,-64.6400,2020-07-27,8,1,7,0,Europe
49054,Turks and Caicos Islands,United Kingdom,21.6940,-71.7979,2020-07-27,99,2,36,61,Europe
49059,Falkland Islands (Malvinas),United Kingdom,-51.7963,-59.5236,2020-07-27,13,0,13,0,Europe

In [ ]:
df_cleaned.equals(df)

False

In [ ]:
df_cleaned.groupby(['Province/State', 'Country/Region'])

In [ ]:
# Ensure Date column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])

print(f"Date range: {df['Date'].min().date()} → {df['Date'].max().date()}")

Date range: 2020-01-22 → 2020-07-27

In [ ]:
pd.date_range(df['Date'].min(), df['Date'].max(), freq='D')

DatetimeIndex(['2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25',
               '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29',
               '2020-01-30', '2020-01-31',
               ...
               '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21',
               '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25',
               '2020-07-26', '2020-07-27'],
              dtype='datetime64[ns]', length=188, freq='D')

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  49068 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [ ]:
# Ensure Date column is in datetime format
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'])

print(f"Date range: {df_cleaned['Date'].min().date()} → {df_cleaned['Date'].max().date()}")

Date range: 2020-01-22 → 2020-07-27

In [ ]:
pd.date_range(df_cleaned['Date'].min(), df_cleaned['Date'].max(), freq='D')

DatetimeIndex(['2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25',
               '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29',
               '2020-01-30', '2020-01-31',
               ...
               '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21',
               '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25',
               '2020-07-26', '2020-07-27'],
              dtype='datetime64[ns]', length=188, freq='D')

[date time index difference](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DatetimeIndex.difference.html)

[PLOTLY](https://plotly.com/python/plot-data-from-csv/)

In [ ]:
def check_date_continuity(g):
    g = g.sort_values('Date')
    all_dates = pd.date_range(g['Date'].min(), g['Date'].max(), freq='D')
    missing = all_dates.difference(g['Date'])
    return pd.Series({
        'start_date': g['Date'].min(),
        'end_date': g['Date'].max(),
        'expected_days': len(all_dates),
        'actual_days': g['Date'].nunique(),
        'missing_days': len(missing),
        'missing_dates': list(missing)
    })

result_dates = (
    df_cleaned.groupby(['Country/Region', 'Province/State'])
      .apply(check_date_continuity, include_groups=True)
      .reset_index()
)

/tmp/ipython-input-2791468007.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(check_date_continuity, include_groups=True)

In [ ]:
result_dates

,Country/Region,Province/State,start_date,end_date,expected_days,actual_days,missing_days,missing_dates
0,Afghanistan,Afghanistan,2020-01-22,2020-07-27,188,188,0,[]
1,Albania,Albania,2020-01-22,2020-07-27,188,188,0,[]
2,Algeria,Algeria,2020-01-22,2020-07-27,188,188,0,[]
3,Andorra,Andorra,2020-01-22,2020-07-27,188,188,0,[]
4,Angola,Angola,2020-01-22,2020-07-27,188,188,0,[]
...,...,...,...,...,...,...,...,...
256,West Bank and Gaza,West Bank and Gaza,2020-01-22,2020-07-27,188,188,0,[]
257,Western Sahara,Western Sahara,2020-01-22,2020-07-27,188,188,0,[]
258,Yemen,Yemen,2020-01-22,2020-07-27,188,188,0,[]
259,Zambia,Zambia,2020-01-22,2020-07-27,188,188,0,[]
260,Zimbabwe,Zimbabwe,2020-01-22,2020-07-27,188,188,0,[]

In [ ]:
df_temp = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]}) # A is a column, B is a column
# Calculate the sum of each column
column_sums_temp = df_temp.apply(np.sum, axis=0)
print(column_sums_temp)

A     6
B    60
dtype: int64

In [ ]:
df_temp

   A   B
0  1  10
1  2  20
2  3  30

In [ ]:
df_temp.apply(np.sum, axis=1) # sum of each row

0    11
1    22
2    33
dtype: int64

In [ ]:
missing_groups_dates = result_dates[result_dates['missing_days'] > 0]
print(missing_groups_dates)

Empty DataFrame
Columns: [Country/Region, Province/State, start_date, end_date, expected_days, actual_days, missing_days, missing_dates]
Index: []

In [ ]:
missing_groups_dates

Empty DataFrame
Columns: [Country/Region, Province/State, start_date, end_date, expected_days, actual_days, missing_days, missing_dates]
Index: []

In [ ]:
df.groupby(['Country/Region', 'Province/State']).apply(
    check_date_continuity, include_groups=False).reset_index()

,Country/Region,Province/State,start_date,end_date,expected_days,actual_days,missing_days,missing_dates
0,Australia,Australian Capital Territory,2020-01-22,2020-07-27,188,188,0,[]
1,Australia,New South Wales,2020-01-22,2020-07-27,188,188,0,[]
2,Australia,Northern Territory,2020-01-22,2020-07-27,188,188,0,[]
3,Australia,Queensland,2020-01-22,2020-07-27,188,188,0,[]
4,Australia,South Australia,2020-01-22,2020-07-27,188,188,0,[]
...,...,...,...,...,...,...,...,...
73,United Kingdom,Falkland Islands (Malvinas),2020-01-22,2020-07-27,188,188,0,[]
74,United Kingdom,Gibraltar,2020-01-22,2020-07-27,188,188,0,[]
75,United Kingdom,Isle of Man,2020-01-22,2020-07-27,188,188,0,[]
76,United Kingdom,Montserrat,2020-01-22,2020-07-27,188,188,0,[]
77,United Kingdom,Turks and Caicos Islands,2020-01-22,2020-07-27,188,188,0,[]

In [ ]:
df_cleaned.groupby(['Country/Region', 'Province/State']).apply(
    check_date_continuity, include_groups=False).reset_index()

,Country/Region,Province/State,start_date,end_date,expected_days,actual_days,missing_days,missing_dates
0,Afghanistan,Afghanistan,2020-01-22,2020-07-27,188,188,0,[]
1,Albania,Albania,2020-01-22,2020-07-27,188,188,0,[]
2,Algeria,Algeria,2020-01-22,2020-07-27,188,188,0,[]
3,Andorra,Andorra,2020-01-22,2020-07-27,188,188,0,[]
4,Angola,Angola,2020-01-22,2020-07-27,188,188,0,[]
...,...,...,...,...,...,...,...,...
256,West Bank and Gaza,West Bank and Gaza,2020-01-22,2020-07-27,188,188,0,[]
257,Western Sahara,Western Sahara,2020-01-22,2020-07-27,188,188,0,[]
258,Yemen,Yemen,2020-01-22,2020-07-27,188,188,0,[]
259,Zambia,Zambia,2020-01-22,2020-07-27,188,188,0,[]
260,Zimbabwe,Zimbabwe,2020-01-22,2020-07-27,188,188,0,[]

In [ ]:
result_dates.head(100)

,Country/Region,Province/State,start_date,end_date,expected_days,actual_days,missing_days,missing_dates
0,Afghanistan,Afghanistan,2020-01-22,2020-07-27,188,188,0,[]
1,Albania,Albania,2020-01-22,2020-07-27,188,188,0,[]
2,Algeria,Algeria,2020-01-22,2020-07-27,188,188,0,[]
3,Andorra,Andorra,2020-01-22,2020-07-27,188,188,0,[]
4,Angola,Angola,2020-01-22,2020-07-27,188,188,0,[]
...,...,...,...,...,...,...,...,...
95,Cyprus,Cyprus,2020-01-22,2020-07-27,188,188,0,[]
96,Czechia,Czechia,2020-01-22,2020-07-27,188,188,0,[]
97,Denmark,Faroe Islands,2020-01-22,2020-07-27,188,188,0,[]
98,Denmark,Mainland Denmark,2020-01-22,2020-07-27,188,188,0,[]
99,Djibouti,Djibouti,2020-01-22,2020-07-27,188,188,0,[]

from the above for each country and provice it is continuous data

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  49068 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  datetime64[ns]
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 3.7+ MB

In [ ]:
df_cleaned.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [ ]:
df_cleaned.isnull().sum().sum()

np.int64(0)

In [ ]:
df_cleaned.duplicated().sum()

np.int64(0)

In [ ]:
# 261 groups of Country and Province, 188 days
261*188

49068

In [ ]:
len(df_cleaned) == 261*188

True

In [ ]:
# check if each min date and max date in group is equal to that of the overall min and max

In [ ]:
# overall min max from original df

overall_minimum_date = df['Date'].min().date()
overall_maximum_date = df['Date'].max().date()

In [ ]:
df_cleaned.groupby(['Country/Region', 'Province/State']).apply(
    lambda g: ((g['Date'].min().date() == overall_minimum_date) and
               (g['Date'].max().date() == overall_maximum_date))
).sum()

/tmp/ipython-input-1315669599.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cleaned.groupby(['Country/Region', 'Province/State']).apply(

np.int64(261)

In [ ]:
df_cleaned.groupby(['Country/Region', 'Province/State']).apply(
    lambda g: ((g['Date'].min().date() == overall_minimum_date) and
               (g['Date'].max().date() == overall_maximum_date))
).all()  # true only if all are true

/tmp/ipython-input-214072288.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cleaned.groupby(['Country/Region', 'Province/State']).apply(

np.True_

In [ ]:
df_cleaned.to_csv('covid_19_cleaned.csv', index=False)